In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
from matplotlib import pyplot as plt

In [4]:
import seaborn as sns

In [5]:
df_train = pd.read_csv('train.csv')

In [6]:
df_train.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved
0,p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,I currently have a differentiated sight word c...,NaN,NaN,My students need 6 Ipod Nano's to create and d...,26,1
1,p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,We strive to provide our diverse population of...,NaN,NaN,My students need matching shirts to wear for d...,1,0
2,p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,We are looking to add some 3Doodler to our cla...,NaN,NaN,My students need the 3doodler. We are an SEM s...,5,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,"The student's project which is totally \""kid-i...",NaN,NaN,My students need balls and other activity equi...,16,0
4,p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,For some reason in our kitchen the water comes...,NaN,NaN,My students need a water filtration system for...,42,1

In [7]:
df_train.shape

(182080, 16)

In [8]:
df_train.groupby('project_is_approved').describe()

                    teacher_number_of_previously_posted_projects             \
                                                           count       mean
project_is_approved
0                                                        27734.0   6.902791
1                                                       154346.0  12.015867


                           std  min  25%  50%  75%    max
project_is_approved
0                    17.684081  0.0  0.0  2.0  6.0  379.0
1                    29.423888  0.0  0.0  2.0  9.0  451.0

# 27k rejected and 154k approved

# USD

In [9]:
df_USD = pd.read_csv("USD.csv")

In [10]:
df_USD.head()

        id  count      USD
0  p000001    4.0   833.63
1  p000002   14.0   630.28
2  p000003    4.0   298.97
3  p000004   95.0  1126.22
4  p000005    4.0   702.31

In [11]:
%matplotlib inline

## project_grade_category

In [12]:
df_train.groupby('project_grade_category').describe()

                       project_is_approved                                     \
                                     count      mean       std  min  25%  50%
project_grade_category
Grades 3-5                         61682.0  0.853977  0.353132  0.0  1.0  1.0
Grades 6-8                         28197.0  0.843459  0.363374  0.0  1.0  1.0
Grades 9-12                        18311.0  0.835236  0.370978  0.0  1.0  1.0
Grades PreK-2                      73890.0  0.847124  0.359870  0.0  1.0  1.0

                                 teacher_number_of_previously_posted_projects  \
                        75%  max                                        count
project_grade_category
Grades 3-5              1.0  1.0                                      61682.0
Grades 6-8              1.0  1.0                                      28197.0
Grades 9-12             1.0  1.0                                      18311.0
Grades PreK-2           1.0  1.0                                      73890.0


                             mean        std  min  25%  50%   75%    max
project_grade_category
Grades 3-5              10.440615  24.603382  0.0  0.0  2.0   9.0  354.0
Grades 6-8              10.762209  25.809061  0.0  0.0  2.0   8.0  272.0
Grades 9-12              9.519742  24.360918  0.0  0.0  2.0   7.0  285.0
Grades PreK-2           12.508689  32.010115  0.0  0.0  3.0  10.0  451.0

## project_subject_categories

In [13]:
df_train.groupby('project_subject_categories').describe()

                                           project_is_approved            \
                                                         count      mean
project_subject_categories
Applied Learning                                        6310.0  0.814897
Applied Learning, Health & Sports                       1018.0  0.813360
Applied Learning, History & Civics                       303.0  0.795380
Applied Learning, Literacy & Language                   3725.0  0.861208
Applied Learning, Math & Science                        1711.0  0.803624
Applied Learning, Music & The Arts                      1241.0  0.809831
Applied Learning, Special Needs                         2481.0  0.811769
Applied Learning, Warmth, Care & Hunger                   22.0  0.636364
Health & Sports                                        16951.0  0.846794
Health & Sports, Applied Learning                        297.0  0.851852
Health & Sports, History & Civics                         67.0  0.820896
Health & Sports, Literacy & Language                    1308.0  0.847859
Health & Sports, Math & Science                          470.0  0.848936
Health & Sports, Music & The Arts                        262.0  0.782443
Health & Sports, Special Needs                          2368.0  0.861064
Health & Sports, Warmth, Care & Hunger                    31.0  0.903226
History & Civics                                        3065.0  0.831974
History & Civics, Applied Learning                        65.0  0.753846
History & Civics, Health & Sports                         20.0  0.900000
History & Civics, Literacy & Language                   2288.0  0.885490
History & Civics, Math & Science                         525.0  0.853333
History & Civics, Music & The Arts                       544.0  0.821691
History & Civics, Special Needs                          417.0  0.815348
History & Civics, Warmth, Care & Hunger                    1.0  0.000000
Literacy & Language                                    39257.0  0.869858
Literacy & Language, Applied Learning                   1038.0  0.859345
Literacy & Language, Health & Sports                     127.0  0.771654
Literacy & Language, History & Civics                   1315.0  0.890494
Literacy & Language, Math & Science                    24499.0  0.867219
Literacy & Language, Music & The Arts                   2878.0  0.838777
Literacy & Language, Special Needs                      6685.0  0.854450
Literacy & Language, Warmth, Care & Hunger                25.0  0.840000
Math & Science                                         28555.0  0.821082
Math & Science, Applied Learning                        2071.0  0.832448
Math & Science, Health & Sports                          697.0  0.780488
Math & Science, History & Civics                        1087.0  0.858326
Math & Science, Literacy & Language                     3843.0  0.861046
Math & Science, Music & The Arts                        2761.0  0.827961
Math & Science, Special Needs                           3010.0  0.825581
Math & Science, Warmth, Care & Hunger                     19.0  0.631579
Music & The Arts                                        8527.0  0.850006
Music & The Arts, Applied Learning                        21.0  0.714286
Music & The Arts, Health & Sports                         32.0  0.656250
Music & The Arts, History & Civics                        29.0  0.793103
Music & The Arts, Special Needs                          235.0  0.863830
Music & The Arts, Warmth, Care & Hunger                    3.0  0.666667
Special Needs                                           7065.0  0.809483
Special Needs, Health & Sports                            64.0  0.765625
Special Needs, Music & The Arts                          521.0  0.827255
Special Needs, Warmth, Care & Hunger                      35.0  0.771429
Warmth, Care & Hunger                                   2191.0  0.921953

                                                                               \
                                                 std  min  25%  50%  75%  max
project_subject_categories
Applied Learning                            0.388412  0.0  1.0  1.0  1.0  1.0
Applied Learning, Health & Sports           0.389814  0.0  1.0  1.0  1.0  1.0
Applied Learning, History & Civics          0.404091  0.0  1.0  1.0  1.0  1.0
Applied Learning, Literacy & Language       0.345776  0.0  1.0  1.0  1.0  1.0
Applied Learning, Math & Science            0.397373  0.0  1.0  1.0  1.0  1.0
Applied Learning, Music & The Arts          0.392593  0.0  1.0  1.0  1.0  1.0
Applied Learning, Special Needs             0.390975  0.0  1.0  1.0  1.0  1.0
Applied Learning, Warmth, Care & Hunger     0.492366  0.0  0.0  1.0  1.0  1.0
Health & Sports                             0.360197  0.0  1.0  1.0  1.0  1.0
Health & Sports, Applied Learning           0.355846  0.0  1.0  1.0  1.0  1.0
Health & Sports, History & Civics           0.386334  0.0  1.0  1.0  1.0  1.0
Health & Sports, Literacy & Language        0.359295  0.0  1.0  1.0  1.0  1.0
Health & Sports, Math & Science             0.358493  0.0  1.0  1.0  1.0  1.0
Health & Sports, Music & The Arts           0.413374  0.0  1.0  1.0  1.0  1.0
Health & Sports, Special Needs              0.345953  0.0  1.0  1.0  1.0  1.0
Health & Sports, Warmth, Care & Hunger      0.300537  0.0  1.0  1.0  1.0  1.0
History & Civics                            0.373950  0.0  1.0  1.0  1.0  1.0
History & Civics, Applied Learning          0.434122  0.0  1.0  1.0  1.0  1.0
History & Civics, Health & Sports           0.307794  0.0  1.0  1.0  1.0  1.0
History & Civics, Literacy & Language       0.318500  0.0  1.0  1.0  1.0  1.0
History & Civics, Math & Science            0.354111  0.0  1.0  1.0  1.0  1.0
History & Civics, Music & The Arts          0.383125  0.0  1.0  1.0  1.0  1.0
History & Civics, Special Needs             0.388481  0.0  1.0  1.0  1.0  1.0
History & Civics, Warmth, Care & Hunger          NaN  0.0  0.0  0.0  0.0  0.0
Literacy & Language                         0.336464  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Applied Learning       0.347833  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Health & Sports        0.421429  0.0  1.0  1.0  1.0  1.0
Literacy & Language, History & Civics       0.312391  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Math & Science         0.339345  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Music & The Arts       0.367800  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Special Needs          0.352681  0.0  1.0  1.0  1.0  1.0
Literacy & Language, Warmth, Care & Hunger  0.374166  0.0  1.0  1.0  1.0  1.0
Math & Science                              0.383290  0.0  1.0  1.0  1.0  1.0
Math & Science, Applied Learning            0.373558  0.0  1.0  1.0  1.0  1.0
Math & Science, Health & Sports             0.414213  0.0  1.0  1.0  1.0  1.0
Math & Science, History & Civics            0.348876  0.0  1.0  1.0  1.0  1.0
Math & Science, Literacy & Language         0.345943  0.0  1.0  1.0  1.0  1.0
Math & Science, Music & The Arts            0.377483  0.0  1.0  1.0  1.0  1.0
Math & Science, Special Needs               0.379532  0.0  1.0  1.0  1.0  1.0
Math & Science, Warmth, Care & Hunger       0.495595  0.0  0.0  1.0  1.0  1.0
Music & The Arts                            0.357087  0.0  1.0  1.0  1.0  1.0
Music & The Arts, Applied Learning          0.462910  0.0  0.0  1.0  1.0  1.0
Music & The Arts, Health & Sports           0.482559  0.0  0.0  1.0  1.0  1.0
Music & The Arts, History & Civics          0.412251  0.0  1.0  1.0  1.0  1.0
Music & The Arts, Special Needs             0.343701  0.0  1.0  1.0  1.0  1.0
Music & The Arts, Warmth, Care & Hunger     0.577350  0.0  0.5  1.0  1.0  1.0
Special Needs                               0.392736  0.0  1.0  1.0  1.0  1.0
Special Needs, Health & Sports              0.426956  0.0  1.0  1.0  1.0  1.0
Special Needs, Music & The Arts             0.378390  0.0  1.0  1.0  1.0  1.0
Special Needs, Warmth, Care & Hunger        0.426043  0.0  1.0  1.0  1.0  1.0
Warmth, Care & Hunger                       0.268306  0.0  1.0  1.0  1.0  1.0

                                           teacher_number_of_previously_posted_projects  \
                                                                                  count
project_subject_categories
Applied Learning                                                                 6310.0
Applied Learning, Health & Sports                                                1018.0
Applied Learning, History & Civics                                                303.0
Applied Learning, Literacy & Language                                            3725.0
Applied Learning, Math & Science                                                 1711.0
Applied Learning, Music & The Arts                                               1241.0
Applied Learning, Special Needs                                                  2481.0
Applied Learning, Warmth, Care & Hunger                                            22.0
Health & Sports                                                                 16951.0
Health & Sports, Applied Learning                                                 297.0
Health & Sports, History & Civics                                                  67.0
Health & Sports, Literacy & Language                                             1308.0
Health & Sports, Math & Science                                                   470.0
Health & Sports, Music & The Arts                                                 262.0
Health & Sports, Special Needs                                                   2368.0
Health & Sports, Warmth, Care & Hunger                                             31.0
History & Civics                                                                 3065.0
History & Civics, Applied Learning                                                 65.0
History & Civics, Health & Sports                                                  20.0
History & Civics, Literacy & Language                                            2288.0
History & Civics, Math & Science                                                  525.0
History & Civics, Music & The Arts                                                544.0
History & Civics, Special Needs                                                   417.0
History & Civics, Warmth, Care & Hunger                                             1.0
Literacy & Language                                                             39257.0
Literacy & Language, Applied Learning                                            1038.0
Literacy & Language, Health & Sports                                              127.0
Literacy & Language, History & Civics                                            1315.0
Literacy & Language, Math & Science                                             24499.0
Literacy & Language, Music & The Arts                                            2878.0
Literacy & Language, Special Needs                                               6685.0
Literacy & Language, Warmth, Care & Hunger                                         25.0
Math & Science                                                                  28555.0
Math & Science, Applied Learning                                                 2071.0
Math & Science, Health & Sports                                                   697.0
Math & Science, History & Civics                                                 1087.0
Math & Science, Literacy & Language                                              3843.0
Math & Science, Music & The Arts                                                 2761.0
Math & Science, Special Needs                                                    3010.0
Math & Science, Warmth, Care & Hunger                                              19.0
Music & The Arts                                                                 8527.0
Music & The Arts, Applied Learning                                                 21.0
Music & The Arts, Health & Sports                                                  32.0
Music & The Arts, History & Civics                                                 29.0
Music & The Arts, Special Needs                                                   235.0
Music & The Arts, Warmth, Care & Hunger                                             3.0
Special Needs                                                                    7065.0
Special Needs, Health & Sports                                                     64.0
Special Needs, Music & The Arts                                                   521.0
Special Needs, Warmth, Care & Hunger                                               35.0
Warmth, Care & Hunger                                                            2191.0

                                                                            \
                                                 mean        std  min  25%
project_subject_categories
Applied Learning                             9.911886  26.563367  0.0  0.0
Applied Learning, Health & Sports           11.103143  27.514762  0.0  0.0
Applied Learning, History & Civics          14.132013  29.417902  0.0  1.0
Applied Learning, Literacy & Language       10.980671  26.452238  0.0  0.0
Applied Learning, Math & Science            11.528930  31.447072  0.0  0.0
Applied Learning, Music & The Arts          18.666398  41.451350  0.0  1.0
Applied Learning, Special Needs              9.478839  26.559816  0.0  0.0
Applied Learning, Warmth, Care & Hunger     28.181818  55.891593  0.0  0.0
Health & Sports                             16.455194  31.321373  0.0  1.0
Health & Sports, Applied Learning            8.471380  27.745830  0.0  0.0
Health & Sports, History & Civics            9.746269  18.227804  0.0  1.0
Health & Sports, Literacy & Language        10.823394  28.338270  0.0  1.0
Health & Sports, Math & Science             10.823404  27.363476  0.0  0.0
Health & Sports, Music & The Arts           20.793893  45.660117  0.0  1.0
Health & Sports, Special Needs              10.810811  25.226371  0.0  0.0
Health & Sports, Warmth, Care & Hunger      20.935484  52.236600  0.0  1.0
History & Civics                            10.204241  26.657056  0.0  0.0
History & Civics, Applied Learning          10.676923  16.870933  0.0  0.0
History & Civics, Health & Sports            5.750000   7.758696  0.0  1.0
History & Civics, Literacy & Language       10.118881  23.848557  0.0  0.0
History & Civics, Math & Science            18.396190  38.040296  0.0  1.0
History & Civics, Music & The Arts          19.062500  39.752917  0.0  1.0
History & Civics, Special Needs             20.043165  36.017464  0.0  1.0
History & Civics, Warmth, Care & Hunger      2.000000        NaN  2.0  2.0
Literacy & Language                          8.965713  23.797369  0.0  0.0
Literacy & Language, Applied Learning       16.842967  39.993338  0.0  1.0
Literacy & Language, Health & Sports        13.464567  30.410367  0.0  1.0
Literacy & Language, History & Civics        7.789354  21.442512  0.0  0.0
Literacy & Language, Math & Science          7.640434  21.347862  0.0  0.0
Literacy & Language, Music & The Arts       18.557331  39.216218  0.0  1.0
Literacy & Language, Special Needs          10.701122  26.906111  0.0  0.0
Literacy & Language, Warmth, Care & Hunger  11.680000  29.731745  0.0  0.0
Math & Science                              10.775311  27.138885  0.0  0.0
Math & Science, Applied Learning            14.986480  36.586933  0.0  0.0
Math & Science, Health & Sports             13.989957  30.685626  0.0  1.0
Math & Science, History & Civics             9.303588  26.068118  0.0  0.0
Math & Science, Literacy & Language         13.162894  29.421182  0.0  1.0
Math & Science, Music & The Arts            23.321985  45.978550  0.0  1.0
Math & Science, Special Needs               10.946844  21.988633  0.0  0.0
Math & Science, Warmth, Care & Hunger       23.684211  47.812194  0.0  2.5
Music & The Arts                            10.907119  25.298922  0.0  0.0
Music & The Arts, Applied Learning          32.571429  68.532161  0.0  1.0
Music & The Arts, Health & Sports            9.968750  27.236698  0.0  0.0
Music & The Arts, History & Civics          17.275862  40.825322  0.0  1.0
Music & The Arts, Special Needs             14.834043  27.969804  0.0  1.0
Music & The Arts, Warmth, Care & Hunger     27.000000  34.641016  7.0  7.0
Special Needs                                7.255768  20.357774  0.0  0.0
Special Needs, Health & Sports              11.125000  31.804712  0.0  0.0
Special Needs, Music & The Arts             27.641075  46.446617  0.0  2.0
Special Needs, Warmth, Care & Hunger        21.542857  38.698186  0.0  0.0
Warmth, Care & Hunger                       35.290278  63.486638  0.0  3.0


                                             50%    75%    max
project_subject_categories
Applied Learning                             2.0   7.00  376.0
Applied Learning, Health & Sports            2.0   7.00  370.0
Applied Learning, History & Civics           3.0  11.00  197.0
Applied Learning, Literacy & Language        2.0   9.00  366.0
Applied Learning, Math & Science             2.0   8.00  373.0
Applied Learning, Music & The Arts           4.0  17.00  367.0
Applied Learning, Special Needs              2.0   7.00  314.0
Applied Learning, Warmth, Care & Hunger      2.0  10.25  193.0
Health & Sports                              5.0  17.00  407.0
Health & Sports, Applied Learning            1.0   5.00  305.0
Health & Sports, History & Civics            3.0  13.00  126.0
Health & Sports, Literacy & Language         2.0   8.00  351.0
Health & Sports, Math & Science              3.0  10.00  322.0
Health & Sports, Music & The Arts            4.0  17.00  372.0
Health & Sports, Special Needs               2.0   9.00  280.0
Health & Sports, Warmth, Care & Hunger       4.0  13.50  279.0
History & Civics                             2.0   8.00  397.0
History & Civics, Applied Learning           1.0  13.00   73.0
History & Civics, Health & Sports            3.0   7.25   32.0
History & Civics, Literacy & Language        2.0   8.00  272.0
History & Civics, Math & Science             4.0  17.00  257.0
History & Civics, Music & The Arts           4.5  19.00  382.0
History & Civics, Special Needs              4.0  19.00  196.0
History & Civics, Warmth, Care & Hunger      2.0   2.00    2.0
Literacy & Language                          2.0   7.00  437.0
Literacy & Language, Applied Learning        3.0  14.00  389.0
Literacy & Language, Health & Sports         3.0  13.00  195.0
Literacy & Language, History & Civics        2.0   6.00  320.0
Literacy & Language, Math & Science          2.0   6.00  404.0
Literacy & Language, Music & The Arts        5.0  16.00  362.0
Literacy & Language, Special Needs           2.0   8.00  311.0
Literacy & Language, Warmth, Care & Hunger   0.0   5.00  129.0
Math & Science                               2.0   8.00  422.0
Math & Science, Applied Learning             3.0  12.00  364.0
Math & Science, Health & Sports              4.0  13.00  269.0
Math & Science, History & Civics             2.0   7.00  322.0
Math & Science, Literacy & Language          3.0  11.00  377.0
Math & Science, Music & The Arts             6.0  22.00  386.0
Math & Science, Special Needs                3.0  11.00  207.0
Math & Science, Warmth, Care & Hunger        4.0  26.00  210.0
Music & The Arts                             2.0   9.00  387.0
Music & The Arts, Applied Learning           2.0  11.00  196.0
Music & The Arts, Health & Sports            1.0  10.50  152.0
Music & The Arts, History & Civics           4.0  10.00  178.0
Music & The Arts, Special Needs              4.0  16.00  204.0
Music & The Arts, Warmth, Care & Hunger      7.0  37.00   67.0
Special Needs                                1.0   6.00  332.0
Special Needs, Health & Sports               2.0   8.00  185.0
Special Needs, Music & The Arts              8.0  34.00  395.0

In [14]:
df = df_train.groupby('project_subject_categories').describe()

In [15]:
df = df['project_is_approved']

In [16]:
df.head()

,count,mean,std,min,25%,50%,75%,max
project_subject_categories,,,,,,,,
Applied Learning,6310.0,0.814897,0.388412,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Health & Sports",1018.0,0.813360,0.389814,0.0,1.0,1.0,1.0,1.0
"Applied Learning, History & Civics",303.0,0.795380,0.404091,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Literacy & Language",3725.0,0.861208,0.345776,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Math & Science",1711.0,0.803624,0.397373,0.0,1.0,1.0,1.0,1.0

In [17]:
df.sort_values('mean')

,count,mean,std,min,25%,50%,75%,max
project_subject_categories,,,,,,,,
"History & Civics, Warmth, Care & Hunger",1.0,0.000000,NaN,0.0,0.0,0.0,0.0,0.0
"Math & Science, Warmth, Care & Hunger",19.0,0.631579,0.495595,0.0,0.0,1.0,1.0,1.0
"Applied Learning, Warmth, Care & Hunger",22.0,0.636364,0.492366,0.0,0.0,1.0,1.0,1.0
"Music & The Arts, Health & Sports",32.0,0.656250,0.482559,0.0,0.0,1.0,1.0,1.0
"Music & The Arts, Warmth, Care & Hunger",3.0,0.666667,0.577350,0.0,0.5,1.0,1.0,1.0
"Music & The Arts, Applied Learning",21.0,0.714286,0.462910,0.0,0.0,1.0,1.0,1.0
"History & Civics, Applied Learning",65.0,0.753846,0.434122,0.0,1.0,1.0,1.0,1.0
"Special Needs, Health & Sports",64.0,0.765625,0.426956,0.0,1.0,1.0,1.0,1.0
"Special Needs, Warmth, Care & Hunger",35.0,0.771429,0.426043,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Health & Sports",127.0,0.771654,0.421429,0.0,1.0,1.0,1.0,1.0
"Math & Science, Health & Sports",697.0,0.780488,0.414213,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Music & The Arts",262.0,0.782443,0.413374,0.0,1.0,1.0,1.0,1.0
"Music & The Arts, History & Civics",29.0,0.793103,0.412251,0.0,1.0,1.0,1.0,1.0
"Applied Learning, History & Civics",303.0,0.795380,0.404091,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Math & Science",1711.0,0.803624,0.397373,0.0,1.0,1.0,1.0,1.0
Special Needs,7065.0,0.809483,0.392736,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Music & The Arts",1241.0,0.809831,0.392593,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Special Needs",2481.0,0.811769,0.390975,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Health & Sports",1018.0,0.813360,0.389814,0.0,1.0,1.0,1.0,1.0
Applied Learning,6310.0,0.814897,0.388412,0.0,1.0,1.0,1.0,1.0
"History & Civics, Special Needs",417.0,0.815348,0.388481,0.0,1.0,1.0,1.0,1.0
"Health & Sports, History & Civics",67.0,0.820896,0.386334,0.0,1.0,1.0,1.0,1.0
Math & Science,28555.0,0.821082,0.383290,0.0,1.0,1.0,1.0,1.0
"History & Civics, Music & The Arts",544.0,0.821691,0.383125,0.0,1.0,1.0,1.0,1.0
"Math & Science, Special Needs",3010.0,0.825581,0.379532,0.0,1.0,1.0,1.0,1.0
"Special Needs, Music & The Arts",521.0,0.827255,0.378390,0.0,1.0,1.0,1.0,1.0
"Math & Science, Music & The Arts",2761.0,0.827961,0.377483,0.0,1.0,1.0,1.0,1.0
History & Civics,3065.0,0.831974,0.373950,0.0,1.0,1.0,1.0,1.0
"Math & Science, Applied Learning",2071.0,0.832448,0.373558,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Music & The Arts",2878.0,0.838777,0.367800,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Warmth, Care & Hunger",25.0,0.840000,0.374166,0.0,1.0,1.0,1.0,1.0
Health & Sports,16951.0,0.846794,0.360197,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Literacy & Language",1308.0,0.847859,0.359295,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Math & Science",470.0,0.848936,0.358493,0.0,1.0,1.0,1.0,1.0
Music & The Arts,8527.0,0.850006,0.357087,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Applied Learning",297.0,0.851852,0.355846,0.0,1.0,1.0,1.0,1.0
"History & Civics, Math & Science",525.0,0.853333,0.354111,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Special Needs",6685.0,0.854450,0.352681,0.0,1.0,1.0,1.0,1.0
"Math & Science, History & Civics",1087.0,0.858326,0.348876,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Applied Learning",1038.0,0.859345,0.347833,0.0,1.0,1.0,1.0,1.0
"Math & Science, Literacy & Language",3843.0,0.861046,0.345943,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Special Needs",2368.0,0.861064,0.345953,0.0,1.0,1.0,1.0,1.0
"Applied Learning, Literacy & Language",3725.0,0.861208,0.345776,0.0,1.0,1.0,1.0,1.0
"Music & The Arts, Special Needs",235.0,0.863830,0.343701,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, Math & Science",24499.0,0.867219,0.339345,0.0,1.0,1.0,1.0,1.0
Literacy & Language,39257.0,0.869858,0.336464,0.0,1.0,1.0,1.0,1.0
"History & Civics, Literacy & Language",2288.0,0.885490,0.318500,0.0,1.0,1.0,1.0,1.0
"Literacy & Language, History & Civics",1315.0,0.890494,0.312391,0.0,1.0,1.0,1.0,1.0
"History & Civics, Health & Sports",20.0,0.900000,0.307794,0.0,1.0,1.0,1.0,1.0
"Health & Sports, Warmth, Care & Hunger",31.0,0.903226,0.300537,0.0,1.0,1.0,1.0,1.0
"Warmth, Care & Hunger",2191.0,0.921953,0.268306,0.0,1.0,1.0,1.0,1.0

In [18]:
df_test = pd.read_csv('test.csv')

/Users/takuyasakaguchi/anaconda/envs/python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [19]:
df_test.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects
0,p233245,5724a0c3ce11008366fff36dab4b943c,Ms.,CA,2016-04-27 13:45:41,Grades PreK-2,Music & The Arts,Visual Arts,Art Will Make You Happy!,My 2nd grade students are amazing! They are v...,My class is made up of 12 boys and 12 girls. ...,My second grade class will really benefit from...,The genorous donations to my project will make...,My students need a drying rack for their art p...,2
1,p096795,445619941dc7cbe81c7be109dc61a56a,Mrs.,SC,2016-04-28 12:43:56,Grades 3-5,"Literacy & Language, Math & Science","Literature & Writing, Mathematics",Keeping up with the TIMEs,Students within the classroom work in small gr...,My students are all very talented young indivi...,"We do a lot of small group, where the student ...",This project is very important to my classroom...,My students need Time Magazines for next year ...,1
2,p236235,e92a4902b1611a189643d6f12c51e6a0,Mrs.,SC,2016-04-29 21:16:05,Grades PreK-2,Math & Science,"Applied Sciences, Mathematics",Building Bridges to Problem Solving,My students share a love of learning. These s...,My class consists of 14 energetic learners. O...,These Fairy Tale Problem Solving STEM kits wil...,These materials will be help my students with ...,My students need to be mentally stimulated to ...,0
3,p233680,8e92622d2985d3faac1de71609c4be72,Mrs.,IA,2016-04-27 22:32:43,Grades PreK-2,Literacy & Language,Literacy,Classroom Library,Reading is the gateway to the soul. Guiding c...,First graders enter the classroom each day rea...,Book bins will help to organize our classroom ...,"When students begin the first grade, many are ...",My students need an organized classroom library.,0
4,p171879,91a3c89981f626d9a0d067c65fb186ce,Mr.,CA,2016-04-27 18:59:15,Grades 6-8,"Music & The Arts, Special Needs","Performing Arts, Special Needs",Reeds so we can Read,"\""Mr. Reyes! I need another reed!\"" I hear t...",We have a diverse population with almost entir...,Each day in my class students consume supplies...,My students come from very troubled homes and ...,My students need reeds to perform in class eac...,1

In [20]:
df_train = df_train.fillna("")

In [21]:
df_test['project_is_approved'] = -1

In [22]:
df_test = df_test.fillna("")

In [23]:
df = pd.concat([df_train, df_test])

In [24]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved
0,p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,I currently have a differentiated sight word c...,,,My students need 6 Ipod Nano's to create and d...,26,1
1,p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,We strive to provide our diverse population of...,,,My students need matching shirts to wear for d...,1,0
2,p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,We are looking to add some 3Doodler to our cla...,,,My students need the 3doodler. We are an SEM s...,5,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,"The student's project which is totally \""kid-i...",,,My students need balls and other activity equi...,16,0
4,p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,For some reason in our kitchen the water comes...,,,My students need a water filtration system for...,42,1

In [25]:
df.tail()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved
78030,p183993,be39c3d9b26cbb91f20435ba45e8451e,Mrs.,AL,2017-04-07 07:48:40,Grades PreK-2,"Applied Learning, Literacy & Language","Early Development, Literature & Writing",iPad Intelligence,I teach a diverse group of creative kindergart...,My students will use the Apple iPad mini durin...,,,My students need one iPad mini to enhance thei...,14,-1
78031,p116343,90957869296e26198b1f162f169f8a55,Ms.,NM,2017-04-25 17:46:26,Grades PreK-2,"Warmth, Care & Hunger","Warmth, Care & Hunger",Clean Clothes Center- Finishing the Cycle,Many of our families do not have access to was...,This clothes dryer will allow students that ha...,,,My students need a clothes dryer to supplement...,1,-1
78032,p210728,692376a473aaf753890e329081b5787c,Mrs.,CA,2017-04-17 17:53:12,Grades 6-8,Literacy & Language,"Literacy, Literature & Writing",Everyday Authors Among Us,My 6th grade students are a lively bunch of in...,"Every year, my 6th grade students write and pu...",,,My students need a variety of materials to use...,4,-1
78033,p060531,0fcaec76e9ea1730e81f2ca8eae5891b,Mrs.,OR,2017-04-19 12:11:59,Grades 3-5,"Warmth, Care & Hunger","Warmth, Care & Hunger",Coat Lockers for Our Classroom!,In our classroom students celebrate their indi...,"At this time, my students place their personal...",,,"My students need coat lockers, so they have a ...",9,-1
78034,p087783,d3fd1b7b0efff1eddbd3fbfe4c00711e,Mrs.,IN,2017-04-27 19:50:35,Grades 3-5,"Literacy & Language, Math & Science","Literacy, Mathematics",A Coffee Shop Classroom,I am a teacher in a Title 1 K-5 elementary sch...,I am gradually switching my classroom from tra...,,,My students need flexible seating arrangements...,0,-1

In [26]:
df = df.set_index('id')

In [27]:
df.head()

,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved
id,,,,,,,,,,,,,,,
p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,I currently have a differentiated sight word c...,,,My students need 6 Ipod Nano's to create and d...,26,1
p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,We strive to provide our diverse population of...,,,My students need matching shirts to wear for d...,1,0
p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,We are looking to add some 3Doodler to our cla...,,,My students need the 3doodler. We are an SEM s...,5,1
p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,"The student's project which is totally \""kid-i...",,,My students need balls and other activity equi...,16,0
p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,For some reason in our kitchen the water comes...,,,My students need a water filtration system for...,42,1

In [28]:
df_USD = df_USD.set_index('id')

In [29]:
df_USD.head()

         count      USD
id
p000001    4.0   833.63
p000002   14.0   630.28
p000003    4.0   298.97
p000004   95.0  1126.22
p000005    4.0   702.31

In [30]:
df = pd.concat([df, df_USD], axis=1, join_axes=[df.index])

In [31]:
df.head()

,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved,count,USD
id,,,,,,,,,,,,,,,,,
p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,I currently have a differentiated sight word c...,,,My students need 6 Ipod Nano's to create and d...,26,1,2.0,899.94
p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,We strive to provide our diverse population of...,,,My students need matching shirts to wear for d...,1,0,1.0,400.00
p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,We are looking to add some 3Doodler to our cla...,,,My students need the 3doodler. We are an SEM s...,5,1,1.0,469.99
p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,"The student's project which is totally \""kid-i...",,,My students need balls and other activity equi...,16,0,5.0,684.47
p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,For some reason in our kitchen the water comes...,,,My students need a water filtration system for...,42,1,1.0,711.00

# word meaning extraction

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer
import sys

In [33]:
tfidf = TfidfVectorizer(stop_words = 'english', max_features = 50)

In [34]:
df['text'] = df.project_title + df.project_essay_1 + df.project_essay_2 + df.project_essay_3 + df.project_essay_4

In [35]:
tfidf.fit(df.text)

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=50, min_df=1,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [36]:
text_result = tfidf.transform(df.text)

In [37]:
text_result.toarray()

array([[ 0.        ,  0.        ,  0.        , ...,  0.1125363 ,
         0.        ,  0.39496268],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08137813,  0.09706347,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [ 0.30572486,  0.        ,  0.        , ...,  0.19096171,
         0.        ,  0.11170136],
       [ 0.        ,  0.        ,  0.        , ...,  0.12400945,
         0.        ,  0.        ],
       [ 0.1109941 ,  0.        ,  0.42540949, ...,  0.10399362,
         0.        ,  0.        ]])

In [38]:
df_text = pd.DataFrame(text_result.toarray())

In [39]:
df_text.head()

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.000000,0.000000,0.0,0.0,0.00000,0.000000,0.000000,0.227272,0.0,0.366501,...,0.529240,0.000000,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963
1,0.000000,0.000000,0.0,0.0,0.23981,0.000000,0.000000,0.000000,0.0,0.184125,...,0.398824,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,0.081378,0.097063,0.0,0.0,0.00000,0.250750,0.061551,0.076991,0.0,0.000000,...,0.493034,0.197225,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,0.000000,0.000000,0.0,0.0,0.00000,0.166199,0.000000,0.076545,0.0,0.329166,...,0.534742,0.000000,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682
4,0.000000,0.000000,0.0,0.0,0.00000,0.450119,0.165734,0.000000,0.0,0.000000,...,0.724126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [40]:
df_text.to_csv('text.csv')

In [41]:
df.to_csv('merged.csv')

In [42]:
df = pd.read_csv('merged.csv')

/Users/takuyasakaguchi/anaconda/envs/python36/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [43]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,project_resource_summary,teacher_number_of_previously_posted_projects,project_is_approved,count,USD,text
0,p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,I currently have a differentiated sight word c...,NaN,NaN,My students need 6 Ipod Nano's to create and d...,26,1,2.0,899.94,Super Sight Word CentersMost of my kindergarte...
1,p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,We strive to provide our diverse population of...,NaN,NaN,My students need matching shirts to wear for d...,1,0,1.0,400.00,Keep Calm and Dance OnOur elementary school is...
2,p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,We are looking to add some 3Doodler to our cla...,NaN,NaN,My students need the 3doodler. We are an SEM s...,5,1,1.0,469.99,Lets 3Doodle to LearnHello;\r\nMy name is Mrs....
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,"The student's project which is totally \""kid-i...",NaN,NaN,My students need balls and other activity equi...,16,0,5.0,684.47,"\""Kid Inspired\"" Equipment to Increase Activit..."
4,p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,For some reason in our kitchen the water comes...,NaN,NaN,My students need a water filtration system for...,42,1,1.0,711.00,We need clean water for our culinary arts clas...

In [44]:
 result = pd.concat([df, df_text], axis=1)

In [45]:
result.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,40,41,42,43,44,45,46,47,48,49
0,p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.529240,0.000000,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963
1,p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.398824,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.493034,0.197225,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.534742,0.000000,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682
4,p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.724126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [46]:
df = result

In [47]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,40,41,42,43,44,45,46,47,48,49
0,p036502,484aaf11257089a66cfedc9461c6bd0a,Ms.,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.529240,0.000000,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963
1,p039565,df72a3ba8089423fa8a94be88060f6ed,Mrs.,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.398824,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,p233823,a9b876a9252e08a55e3d894150f75ba3,Ms.,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.493034,0.197225,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,Mr.,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.534742,0.000000,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682
4,p013780,a63b5547a7239eae4c1872670848e61a,Mr.,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.724126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [48]:
df.tail()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,40,41,42,43,44,45,46,47,48,49
260110,p183993,be39c3d9b26cbb91f20435ba45e8451e,Mrs.,AL,2017-04-07 07:48:40,Grades PreK-2,"Applied Learning, Literacy & Language","Early Development, Literature & Writing",iPad Intelligence,I teach a diverse group of creative kindergart...,...,0.476106,0.209498,0.329788,0.383793,0.084273,0.000000,0.000000,0.000000,0.220552,0.094749
260111,p116343,90957869296e26198b1f162f169f8a55,Ms.,NM,2017-04-25 17:46:26,Grades PreK-2,"Warmth, Care & Hunger","Warmth, Care & Hunger",Clean Clothes Center- Finishing the Cycle,Many of our families do not have access to was...,...,0.404824,0.178133,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
260112,p210728,692376a473aaf753890e329081b5787c,Mrs.,CA,2017-04-17 17:53:12,Grades 6-8,Literacy & Language,"Literacy, Literature & Writing",Everyday Authors Among Us,My 6th grade students are a lively bunch of in...,...,0.729675,0.000000,0.000000,0.000000,0.198702,0.114746,0.257635,0.190962,0.000000,0.111701
260113,p060531,0fcaec76e9ea1730e81f2ca8eae5891b,Mrs.,OR,2017-04-19 12:11:59,Grades 3-5,"Warmth, Care & Hunger","Warmth, Care & Hunger",Coat Lockers for Our Classroom!,In our classroom students celebrate their indi...,...,0.656096,0.000000,0.000000,0.293825,0.000000,0.000000,0.000000,0.124009,0.000000,0.000000
260114,p087783,d3fd1b7b0efff1eddbd3fbfe4c00711e,Mrs.,IN,2017-04-27 19:50:35,Grades 3-5,"Literacy & Language, Math & Science","Literacy, Mathematics",A Coffee Shop Classroom,I am a teacher in a Title 1 K-5 elementary sch...,...,0.427932,0.000000,0.000000,0.123200,0.000000,0.249954,0.000000,0.103994,0.000000,0.000000

In [49]:
df = df.fillna('')

# labeling

In [50]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [51]:
le.fit(df.teacher_prefix)

LabelEncoder()

In [52]:
le.transform(df.teacher_prefix)

array([4, 3, 4, ..., 3, 3, 3])

In [53]:
df['teacher_prefix'] = le.transform(df.teacher_prefix)

In [54]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,40,41,42,43,44,45,46,47,48,49
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,NV,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.529240,0.000000,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,GA,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.398824,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,UT,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.493034,0.197225,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,NC,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.534742,0.000000,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682
4,p013780,a63b5547a7239eae4c1872670848e61a,2,CA,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.724126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [55]:
le.fit(df.school_state)

LabelEncoder()

In [56]:
le.transform(df.school_state)

array([33, 10, 44, ...,  4, 37, 15])

In [57]:
df['school_state'] = le.transform(df.school_state)

In [58]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,40,41,42,43,44,45,46,47,48,49
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.529240,0.000000,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.398824,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.493034,0.197225,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.534742,0.000000,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.724126,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [59]:
df.iloc[0]['project_submitted_datetime'].split("-")

['2016', '11', '18 14:45:59']

In [60]:
df.iloc[0]['project_submitted_datetime'].split("-")[0]

'2016'

In [61]:
df.iloc[0]['project_submitted_datetime'].split("-")[1]

'11'

In [62]:
 df_train['project_submitted_datetime'].apply(lambda row: (int(row.split("-")[0])))

0         2016
1         2017
2         2017
3         2016
4         2016
5         2016
6         2016
7         2016
8         2016
9         2016
10        2017
11        2016
12        2016
13        2016
14        2017
15        2016
16        2016
17        2017
18        2016
19        2016
20        2016
21        2016
22        2016
23        2016
24        2016
25        2016
26        2017
27        2016
28        2016
29        2016
          ...
182050    2016
182051    2017
182052    2016
182053    2016
182054    2017
182055    2017
182056    2016
182057    2017
182058    2017
182059    2016
182060    2016
182061    2016
182062    2016
182063    2016
182064    2016
182065    2017
182066    2016
182067    2016
182068    2016
182069    2016
182070    2017
182071    2016
182072    2016
182073    2016
182074    2016
182075    2016
182076    2017
182077    2017
182078    2016
182079    2016
Name: project_submitted_datetime, Length: 182080, dtype: int64

In [63]:
df['year'] =  df['project_submitted_datetime'].apply(lambda row: (int(row.split("-")[0])))

In [64]:
df['month'] = df['project_submitted_datetime'].apply(lambda row: (int(row.split("-")[1])))

In [65]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,Grades PreK-2,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,Grades 3-5,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,Grades 3-5,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,Grades 3-5,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,Grades 6-8,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [66]:
le.fit(df.project_grade_category)

LabelEncoder()

In [67]:
le.transform(df.project_grade_category)

array([3, 0, 0, ..., 1, 0, 0])

In [68]:
df['project_grade_category'] = le.transform(df.project_grade_category)

In [69]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,Literacy & Language,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,"Music & The Arts, Health & Sports","Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,"Math & Science, Literacy & Language","Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,Health & Sports,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,Health & Sports,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [70]:
le.fit(df.project_subject_categories)
le.transform(df.project_subject_categories)
df['project_subject_categories'] = le.transform(df.project_subject_categories)

In [71]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,Literacy,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,"Performing Arts, Team Sports",Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,"Applied Sciences, Literature & Writing",Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,Health & Wellness,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,Health & Wellness,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [72]:
le.fit(df.project_subject_subcategories)
le.transform(df.project_subject_subcategories)
df['project_subject_subcategories'] = le.transform(df.project_subject_subcategories)

In [73]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

# simply convert essay to word count

In [74]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,Super Sight Word Centers,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,Keep Calm and Dance On,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,Lets 3Doodle to Learn,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,"\""Kid Inspired\"" Equipment to Increase Activit...",My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,We need clean water for our culinary arts class!,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [75]:
 df.project_title = df['project_title'].apply(lambda row: len(row.split(" ")))

In [76]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,4,Most of my kindergarten students come from low...,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,5,Our elementary school is a culturally rich sch...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,4,Hello;\r\nMy name is Mrs. Brotherton. I teach ...,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,10,My students are the greatest students but are ...,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,9,My students are athletes and students who are ...,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [77]:
 df.project_essay_1 = df['project_essay_1'].apply(lambda row: len(row.split(" ")))

In [78]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,4,170,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,5,94,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,4,135,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,10,206,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,9,84,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [79]:
 df.project_essay_2 = df['project_essay_2'].apply(lambda row: len(row.split(" ")))

In [80]:
 df.project_essay_3 = df['project_essay_3'].apply(lambda row: len(row.split(" ")))

In [81]:
 df.project_essay_4 = df['project_essay_4'].apply(lambda row: len(row.split(" ")))

In [82]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,4,170,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,5,94,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,4,135,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,10,206,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,9,84,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [83]:
 df.project_resource_summary = df['project_resource_summary'].apply(lambda row: len(row.split(" ")))

In [84]:
df.head()

,id,teacher_id,teacher_prefix,school_state,project_submitted_datetime,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,...,42,43,44,45,46,47,48,49,year,month
0,p036502,484aaf11257089a66cfedc9461c6bd0a,4,33,2016-11-18 14:45:59,3,24,328,4,170,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,p039565,df72a3ba8089423fa8a94be88060f6ed,3,10,2017-04-26 15:57:28,0,42,400,5,94,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,p233823,a9b876a9252e08a55e3d894150f75ba3,4,44,2017-01-01 22:57:44,0,36,17,4,135,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,p185307,525fdbb6ec7f538a48beebaa0a51b24f,2,27,2016-08-12 15:42:11,0,8,300,10,206,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,p013780,a63b5547a7239eae4c1872670848e61a,2,4,2016-08-06 09:09:11,1,8,300,9,84,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [85]:
df.columns.values

array(['id', 'teacher_id', 'teacher_prefix', 'school_state',
       'project_submitted_datetime', 'project_grade_category',
       'project_subject_categories', 'project_subject_subcategories',
       'project_title', 'project_essay_1', 'project_essay_2',
       'project_essay_3', 'project_essay_4', 'project_resource_summary',
       'teacher_number_of_previously_posted_projects',
       'project_is_approved', 'count', 'USD', 'text', 0, 1, 2, 3, 4, 5, 6,
       7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 'year', 'month'], dtype=object)

In [86]:
selected_columns = ['teacher_prefix', 'school_state',
       'project_grade_category',
       'project_subject_categories', 'project_subject_subcategories',
       'project_title', 'project_essay_1', 'project_essay_2',
       'project_essay_3', 'project_essay_4', 'project_resource_summary',
       'teacher_number_of_previously_posted_projects',
       'project_is_approved', 'count', 'USD',  0, 1, 2, 3, 4, 5, 6,
       7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 'year', 'month']

In [87]:
df = df[selected_columns]

In [89]:
df.head()

,teacher_prefix,school_state,project_grade_category,project_subject_categories,project_subject_subcategories,project_title,project_essay_1,project_essay_2,project_essay_3,project_essay_4,...,42,43,44,45,46,47,48,49,year,month
0,4,33,3,24,328,4,170,142,1,1,...,0.000000,0.0,0.117098,0.135243,0.151828,0.112536,0.0,0.394963,2016,11
1,3,10,0,42,400,5,94,102,1,1,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,4
2,4,44,0,36,17,4,135,101,1,1,...,0.103489,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2017,1
3,2,27,0,8,300,10,206,202,1,1,...,0.000000,0.0,0.000000,0.182199,0.000000,0.000000,0.0,0.088682,2016,8
4,2,4,1,8,300,9,84,108,1,1,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,2016,8

In [90]:
train = df[df.project_is_approved>-1]

In [91]:
test = df[df.project_is_approved==-1]

In [92]:
y_train  = train.pop('project_is_approved')

In [93]:
x_train = train

In [94]:
y_test = test.pop('project_is_approved')

In [95]:
x_test = test

# ML

In [96]:
from sklearn.cross_validation import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn import metrics

/Users/takuyasakaguchi/anaconda/envs/python36/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [97]:
from sklearn.ensemble import RandomForestClassifier

Xtrain, Xtest, ytrain, ytest = train_test_split(x_train, y_train, random_state=0)
clf = RandomForestClassifier(n_estimators=100, random_state=0)
clf.fit(Xtrain, ytrain)
ypred = clf.predict(Xtest)
metrics.accuracy_score(ypred, ytest)

0.84837434094903341

In [98]:
from sklearn.ensemble import GradientBoostingClassifier
Xtrain, Xtest, ytrain, ytest = train_test_split(x_train, y_train, random_state=0)
gbt = GradientBoostingClassifier(max_depth=5, n_estimators=100)
gbt.fit(Xtrain, ytrain)
ypred = gbt.predict(Xtest)
metrics.accuracy_score(ypred, ytest)

0.8485500878734622

In [99]:
from sklearn.ensemble import GradientBoostingClassifier
Xtrain, Xtest, ytrain, ytest = train_test_split(x_train, y_train, random_state=0)
gbt = GradientBoostingClassifier(max_depth=6, n_estimators=200)
gbt.fit(Xtrain, ytrain)
ypred = gbt.predict(Xtest)
metrics.accuracy_score(ypred, ytest)

0.84793497363796133

In [100]:
from sklearn.ensemble import GradientBoostingClassifier
Xtrain, Xtest, ytrain, ytest = train_test_split(x_train, y_train, random_state=0)
gbt = GradientBoostingClassifier(max_depth=4, n_estimators=90)
gbt.fit(Xtrain, ytrain)
ypred = gbt.predict(Xtest)
metrics.accuracy_score(ypred, ytest)

0.84898945518453428

In [101]:
results = gbt.predict_proba(x_test)

In [102]:
results

array([[ 0.08001549,  0.91998451],
       [ 0.05674828,  0.94325172],
       [ 0.06013214,  0.93986786],
       ...,
       [ 0.11978068,  0.88021932],
       [ 0.03276144,  0.96723856],
       [ 0.31181312,  0.68818688]])

In [103]:
results[:,1]

array([ 0.91998451,  0.94325172,  0.93986786, ...,  0.88021932,
        0.96723856,  0.68818688])

In [105]:
df_submission = pd.read_csv('sample_submission.csv')

In [106]:
df_submission.head()

        id  project_is_approved
0  p233245             0.847682
1  p096795             0.847682
2  p236235             0.847682
3  p233680             0.847682
4  p171879             0.847682

In [107]:
df_submission.project_is_approved = results[:,1]

In [108]:
df_submission.head()

        id  project_is_approved
0  p233245             0.919985
1  p096795             0.943252
2  p236235             0.939868
3  p233680             0.898252
4  p171879             0.866968

In [109]:
df_submission.to_csv('submission_4.csv', index = False)

# XGBoost

In [110]:
import xgboost as xgb

In [111]:
dtrain = xgb.DMatrix(Xtrain, ytrain)
dvalid = xgb.DMatrix(Xtest, ytest)

In [112]:
dfinal = xgb.DMatrix(x_test, y_test)

In [113]:
import time

In [114]:
num_boost_round = 4000

In [115]:
eta = 0.005
max_depth = 7
subsample = 0.5
colsample_bytree = 0.5
start_time = time.time()

print('XGBoost params. ETA: {}, MAX_DEPTH: {}, SUBSAMPLE: {}, COLSAMPLE_BY_TREE: {}'.format(eta, max_depth, subsample, colsample_bytree))
params = {
        "objective": "binary:logistic",
        "booster" : "gbtree",
        "eval_metric": "logloss",
        "eta": eta,
        "tree_method": 'exact',
        "max_depth": max_depth,
        "subsample": subsample,
        "colsample_bytree": colsample_bytree,
        "silent": 1,
        "seed": 0
}

early_stopping_rounds = 15
test_size = 0.3

XGBoost params. ETA: 0.005, MAX_DEPTH: 7, SUBSAMPLE: 0.5, COLSAMPLE_BY_TREE: 0.5

In [116]:
watchlist = [(dtrain, 'train'), (dvalid, 'eval')]
gbm = xgb.train(params, dtrain, num_boost_round, evals=watchlist, early_stopping_rounds=early_stopping_rounds, verbose_eval=True)

[0]	train-logloss:0.690528	eval-logloss:0.690552
Multiple eval metrics have been passed: 'eval-logloss' will be used for early stopping.

Will train until eval-logloss hasn't improved in 15 rounds.
[1]	train-logloss:0.687909	eval-logloss:0.687959
[2]	train-logloss:0.685487	eval-logloss:0.685555
[3]	train-logloss:0.682943	eval-logloss:0.683034
[4]	train-logloss:0.680547	eval-logloss:0.680657
[5]	train-logloss:0.678045	eval-logloss:0.678183
[6]	train-logloss:0.675585	eval-logloss:0.675742
[7]	train-logloss:0.673254	eval-logloss:0.673432
[8]	train-logloss:0.670869	eval-logloss:0.671072
[9]	train-logloss:0.66861	eval-logloss:0.668832
[10]	train-logloss:0.666347	eval-logloss:0.666587
[11]	train-logloss:0.663959	eval-logloss:0.66422
[12]	train-logloss:0.661753	eval-logloss:0.662035
[13]	train-logloss:0.659434	eval-logloss:0.659738
[14]	train-logloss:0.657156	eval-logloss:0.657479
[15]	train-logloss:0.65499	eval-logloss:0.655333
[16]	train-logloss:0.652788	eval-logloss:0.653154
[17]	train-logloss:0.650586	eval-logloss:0.65097
[18]	train-logloss:0.648362	eval-logloss:0.648768
[19]	train-logloss:0.646177	eval-logloss:0.646596
[20]	train-logloss:0.644017	eval-logloss:0.644458
[21]	train-logloss:0.64184	eval-logloss:0.642305
[22]	train-logloss:0.639733	eval-logloss:0.640217
[23]	train-logloss:0.637722	eval-logloss:0.638224
[24]	train-logloss:0.635638	eval-logloss:0.636161
[25]	train-logloss:0.633672	eval-logloss:0.634217
[26]	train-logloss:0.631617	eval-logloss:0.632177
[27]	train-logloss:0.629595	eval-logloss:0.630175
[28]	train-logloss:0.627695	eval-logloss:0.628291
[29]	train-logloss:0.625817	eval-logloss:0.626431
[30]	train-logloss:0.623829	eval-logloss:0.62447
[31]	train-logloss:0.621991	eval-logloss:0.622646
[32]	train-logloss:0.62016	eval-logloss:0.620832
[33]	train-logloss:0.618322	eval-logloss:0.619015
[34]	train-logloss:0.616524	eval-logloss:0.617237
[35]	train-logloss:0.614762	eval-logloss:0.615489
[36]	train-logloss:0.612989	eval-logloss:0.613736
[37]	train-logloss:0.611117	eval-logloss:0.611887
[38]	train-logloss:0.609375	eval-logloss:0.610158
[39]	train-logloss:0.607526	eval-logloss:0.608325
[40]	train-logloss:0.605685	eval-logloss:0.60651
[41]	train-logloss:0.604011	eval-logloss:0.604849
[42]	train-logloss:0.602236	eval-logloss:0.603096
[43]	train-logloss:0.600478	eval-logloss:0.601359
[44]	train-logloss:0.598822	eval-logloss:0.599724
[45]	train-logloss:0.597177	eval-logloss:0.598098
[46]	train-logloss:0.595577	eval-logloss:0.596518
[47]	train-logloss:0.593974	eval-logloss:0.594933
[48]	train-logloss:0.592391	eval-logloss:0.593368
[49]	train-logloss:0.590793	eval-logloss:0.591788
[50]	train-logloss:0.589236	eval-logloss:0.590247
[51]	train-logloss:0.587567	eval-logloss:0.588606
[52]	train-logloss:0.586043	eval-logloss:0.587093
[53]	train-logloss:0.584411	eval-logloss:0.58548
[54]	train-logloss:0.582915	eval-logloss:0.584001
[55]	train-logloss:0.581414	eval-logloss:0.582519
[56]	train-logloss:0.579921	eval-logloss:0.581043
[57]	train-logloss:0.578457	eval-logloss:0.579598
[58]	train-logloss:0.576899	eval-logloss:0.578059
[59]	train-logloss:0.575443	eval-logloss:0.57662
[60]	train-logloss:0.574022	eval-logloss:0.57522
[61]	train-logloss:0.572469	eval-logloss:0.573692
[62]	train-logloss:0.570933	eval-logloss:0.572179
[63]	train-logloss:0.569531	eval-logloss:0.570798
[64]	train-logloss:0.568137	eval-logloss:0.569424
[65]	train-logloss:0.566756	eval-logloss:0.568069
[66]	train-logloss:0.565415	eval-logloss:0.566744
[67]	train-logloss:0.564081	eval-logloss:0.565424
[68]	train-logloss:0.562666	eval-logloss:0.564028
[69]	train-logloss:0.561345	eval-logloss:0.562723
[70]	train-logloss:0.560027	eval-logloss:0.561422
[71]	train-logloss:0.558717	eval-logloss:0.560128
[72]	train-logloss:0.55733	eval-logloss:0.558763
[73]	train-logloss:0.556071	eval-logloss:0.557519
[74]	train-logloss:0.5547	eval-logloss:0.556163
[75]	train-logloss:0.55331	eval-logloss:0.554796
[76]	train-logloss:0.551946	eval-logloss:0.553452
[77]	train-logloss:0.550599	eval-logloss:0.552125
[78]	train-logloss:0.549285	eval-logloss:0.550829
[79]	train-logloss:0.547974	eval-logloss:0.54954
[80]	train-logloss:0.546778	eval-logloss:0.548364
[81]	train-logloss:0.545595	eval-logloss:0.547199
[82]	train-logloss:0.544302	eval-logloss:0.545924
[83]	train-logloss:0.543155	eval-logloss:0.544794
[84]	train-logloss:0.541992	eval-logloss:0.543651
[85]	train-logloss:0.54073	eval-logloss:0.542413
[86]	train-logloss:0.53958	eval-logloss:0.54128
[87]	train-logloss:0.538315	eval-logloss:0.540038
[88]	train-logloss:0.537174	eval-logloss:0.538921
[89]	train-logloss:0.535933	eval-logloss:0.537698
[90]	train-logloss:0.534826	eval-logloss:0.536608
[91]	train-logloss:0.533634	eval-logloss:0.53544
[92]	train-logloss:0.532451	eval-logloss:0.534279
[93]	train-logloss:0.531246	eval-logloss:0.533093
[94]	train-logloss:0.530174	eval-logloss:0.532039
[95]	train-logloss:0.529009	eval-logloss:0.530892
[96]	train-logloss:0.52787	eval-logloss:0.529771
[97]	train-logloss:0.526734	eval-logloss:0.52866
[98]	train-logloss:0.525694	eval-logloss:0.527639
[99]	train-logloss:0.524566	eval-logloss:0.526539
[100]	train-logloss:0.523549	eval-logloss:0.525541
[101]	train-logloss:0.52256	eval-logloss:0.52457
[102]	train-logloss:0.521445	eval-logloss:0.523478
[103]	train-logloss:0.520347	eval-logloss:0.522402
[104]	train-logloss:0.51936	eval-logloss:0.521431
[105]	train-logloss:0.518289	eval-logloss:0.520378
[106]	train-logloss:0.517223	eval-logloss:0.519331
[107]	train-logloss:0.516269	eval-logloss:0.518397
[108]	train-logloss:0.515206	eval-logloss:0.517361
[109]	train-logloss:0.514183	eval-logloss:0.516356
[110]	train-logloss:0.513143	eval-logloss:0.515329
[111]	train-logloss:0.51214	eval-logloss:0.514344
[112]	train-logloss:0.511239	eval-logloss:0.513459
[113]	train-logloss:0.51034	eval-logloss:0.512582
[114]	train-logloss:0.509438	eval-logloss:0.511698
[115]	train-logloss:0.508526	eval-logloss:0.510807
[116]	train-logloss:0.507639	eval-logloss:0.509941
[117]	train-logloss:0.506734	eval-logloss:0.509056
[118]	train-logloss:0.505763	eval-logloss:0.508106
[119]	train-logloss:0.504798	eval-logloss:0.507164
[120]	train-logloss:0.503839	eval-logloss:0.506218
[121]	train-logloss:0.50298	eval-logloss:0.50538
[122]	train-logloss:0.502007	eval-logloss:0.504426
[123]	train-logloss:0.501104	eval-logloss:0.503542
[124]	train-logloss:0.50017	eval-logloss:0.502631
[125]	train-logloss:0.499337	eval-logloss:0.501823
[126]	train-logloss:0.498435	eval-logloss:0.500946
[127]	train-logloss:0.497525	eval-logloss:0.500058
[128]	train-logloss:0.496694	eval-logloss:0.499246
[129]	train-logloss:0.495779	eval-logloss:0.498349
[130]	train-logloss:0.494908	eval-logloss:0.4975
[131]	train-logloss:0.494117	eval-logloss:0.496732
[132]	train-logloss:0.493347	eval-logloss:0.495979
[133]	train-logloss:0.492475	eval-logloss:0.49513
[134]	train-logloss:0.491705	eval-logloss:0.494372
[135]	train-logloss:0.490917	eval-logloss:0.493605
[136]	train-logloss:0.490159	eval-logloss:0.492864
[137]	train-logloss:0.489284	eval-logloss:0.49201
[138]	train-logloss:0.48843	eval-logloss:0.491171
[139]	train-logloss:0.487685	eval-logloss:0.49044
[140]	train-logloss:0.486847	eval-logloss:0.489627
[141]	train-logloss:0.486034	eval-logloss:0.488837
[142]	train-logloss:0.485197	eval-logloss:0.488017
[143]	train-logloss:0.484413	eval-logloss:0.487254
[144]	train-logloss:0.483619	eval-logloss:0.486478
[145]	train-logloss:0.48282	eval-logloss:0.485703
[146]	train-logloss:0.482013	eval-logloss:0.484921
[147]	train-logloss:0.481312	eval-logloss:0.484237
[148]	train-logloss:0.480539	eval-logloss:0.483485
[149]	train-logloss:0.479752	eval-logloss:0.482714
[150]	train-logloss:0.478982	eval-logloss:0.481967
[151]	train-logloss:0.47822	eval-logloss:0.481223
[152]	train-logloss:0.477557	eval-logloss:0.480575
[153]	train-logloss:0.476834	eval-logloss:0.479867
[154]	train-logloss:0.476184	eval-logloss:0.479233
[155]	train-logloss:0.475509	eval-logloss:0.478585
[156]	train-logloss:0.474771	eval-logloss:0.477866
[157]	train-logloss:0.47402	eval-logloss:0.477133
[158]	train-logloss:0.473404	eval-logloss:0.476533
[159]	train-logloss:0.472775	eval-logloss:0.475922
[160]	train-logloss:0.472145	eval-logloss:0.475311

[161]	train-logloss:0.471424	eval-logloss:0.474609
[162]	train-logloss:0.470714	eval-logloss:0.473915
[163]	train-logloss:0.470012	eval-logloss:0.47323
[164]	train-logloss:0.469397	eval-logloss:0.472633
[165]	train-logloss:0.468768	eval-logloss:0.472028
[166]	train-logloss:0.468155	eval-logloss:0.471438
[167]	train-logloss:0.467566	eval-logloss:0.470865
[168]	train-logloss:0.466891	eval-logloss:0.47021
[169]	train-logloss:0.466226	eval-logloss:0.469567
[170]	train-logloss:0.465645	eval-logloss:0.469004
[171]	train-logloss:0.46498	eval-logloss:0.468364
[172]	train-logloss:0.464299	eval-logloss:0.467701
[173]	train-logloss:0.463731	eval-logloss:0.467153
[174]	train-logloss:0.463071	eval-logloss:0.466516
[175]	train-logloss:0.462495	eval-logloss:0.465961
[176]	train-logloss:0.461863	eval-logloss:0.46535
[177]	train-logloss:0.461202	eval-logloss:0.464708
[178]	train-logloss:0.460644	eval-logloss:0.46417
[179]	train-logloss:0.459995	eval-logloss:0.463544
[180]	train-logloss:0.459388	eval-logloss:0.462956
[181]	train-logloss:0.458862	eval-logloss:0.462449
[182]	train-logloss:0.458259	eval-logloss:0.461869
[183]	train-logloss:0.457739	eval-logloss:0.461367
[184]	train-logloss:0.457229	eval-logloss:0.460871
[185]	train-logloss:0.456606	eval-logloss:0.460271
[186]	train-logloss:0.456042	eval-logloss:0.459726
[187]	train-logloss:0.45552	eval-logloss:0.459223
[188]	train-logloss:0.454937	eval-logloss:0.458665
[189]	train-logloss:0.45443	eval-logloss:0.458176
[190]	train-logloss:0.453866	eval-logloss:0.457632
[191]	train-logloss:0.453287	eval-logloss:0.45707
[192]	train-logloss:0.452792	eval-logloss:0.456591
[193]	train-logloss:0.452202	eval-logloss:0.456022
[194]	train-logloss:0.451725	eval-logloss:0.455562
[195]	train-logloss:0.451247	eval-logloss:0.455101
[196]	train-logloss:0.450774	eval-logloss:0.454648
[197]	train-logloss:0.450249	eval-logloss:0.454141
[198]	train-logloss:0.449785	eval-logloss:0.453696
[199]	train-logloss:0.44924	eval-logloss:0.45317
[200]	train-logloss:0.448705	eval-logloss:0.452656
[201]	train-logloss:0.448242	eval-logloss:0.452215
[202]	train-logloss:0.447713	eval-logloss:0.451707
[203]	train-logloss:0.447247	eval-logloss:0.451264
[204]	train-logloss:0.446707	eval-logloss:0.450745
[205]	train-logloss:0.446263	eval-logloss:0.450319
[206]	train-logloss:0.445748	eval-logloss:0.449824
[207]	train-logloss:0.445241	eval-logloss:0.44934
[208]	train-logloss:0.444722	eval-logloss:0.448842
[209]	train-logloss:0.444211	eval-logloss:0.448351
[210]	train-logloss:0.443773	eval-logloss:0.447934
[211]	train-logloss:0.443341	eval-logloss:0.447516
[212]	train-logloss:0.442922	eval-logloss:0.447119
[213]	train-logloss:0.442441	eval-logloss:0.446661
[214]	train-logloss:0.442026	eval-logloss:0.446263
[215]	train-logloss:0.441515	eval-logloss:0.445772
[216]	train-logloss:0.441083	eval-logloss:0.445359
[217]	train-logloss:0.440599	eval-logloss:0.444897
[218]	train-logloss:0.440183	eval-logloss:0.444503
[219]	train-logloss:0.439691	eval-logloss:0.444036
[220]	train-logloss:0.439286	eval-logloss:0.443648
[221]	train-logloss:0.438837	eval-logloss:0.443215
[222]	train-logloss:0.43843	eval-logloss:0.442827
[223]	train-logloss:0.438046	eval-logloss:0.442463
[224]	train-logloss:0.437595	eval-logloss:0.442036
[225]	train-logloss:0.437137	eval-logloss:0.441599
[226]	train-logloss:0.43676	eval-logloss:0.44124
[227]	train-logloss:0.436375	eval-logloss:0.440875
[228]	train-logloss:0.435925	eval-logloss:0.440451
[229]	train-logloss:0.435488	eval-logloss:0.440031
[230]	train-logloss:0.435065	eval-logloss:0.439628
[231]	train-logloss:0.434611	eval-logloss:0.439204
[232]	train-logloss:0.434239	eval-logloss:0.43885
[233]	train-logloss:0.433801	eval-logloss:0.43843
[234]	train-logloss:0.433444	eval-logloss:0.438091
[235]	train-logloss:0.433012	eval-logloss:0.437681
[236]	train-logloss:0.432645	eval-logloss:0.437334
[237]	train-logloss:0.432287	eval-logloss:0.436998
[238]	train-logloss:0.431864	eval-logloss:0.436597
[239]	train-logloss:0.431451	eval-logloss:0.436203
[240]	train-logloss:0.431032	eval-logloss:0.435804
[241]	train-logloss:0.430614	eval-logloss:0.435404
[242]	train-logloss:0.430272	eval-logloss:0.435079
[243]	train-logloss:0.429856	eval-logloss:0.434691
[244]	train-logloss:0.429459	eval-logloss:0.434315
[245]	train-logloss:0.429042	eval-logloss:0.433925
[246]	train-logloss:0.428728	eval-logloss:0.433631
[247]	train-logloss:0.42831	eval-logloss:0.433236
[248]	train-logloss:0.427986	eval-logloss:0.432933
[249]	train-logloss:0.427609	eval-logloss:0.432571
[250]	train-logloss:0.427281	eval-logloss:0.432259
[251]	train-logloss:0.426891	eval-logloss:0.431893
[252]	train-logloss:0.426566	eval-logloss:0.431591
[253]	train-logloss:0.426246	eval-logloss:0.431291
[254]	train-logloss:0.425853	eval-logloss:0.430916
[255]	train-logloss:0.425498	eval-logloss:0.430581
[256]	train-logloss:0.425109	eval-logloss:0.430208
[257]	train-logloss:0.424747	eval-logloss:0.429867
[258]	train-logloss:0.424439	eval-logloss:0.429581
[259]	train-logloss:0.424143	eval-logloss:0.429306
[260]	train-logloss:0.423761	eval-logloss:0.42894
[261]	train-logloss:0.42347	eval-logloss:0.428669
[262]	train-logloss:0.423118	eval-logloss:0.428337
[263]	train-logloss:0.422786	eval-logloss:0.428021
[264]	train-logloss:0.422441	eval-logloss:0.427701
[265]	train-logloss:0.422094	eval-logloss:0.427372
[266]	train-logloss:0.421809	eval-logloss:0.427113
[267]	train-logloss:0.42151	eval-logloss:0.426836
[268]	train-logloss:0.421221	eval-logloss:0.426572
[269]	train-logloss:0.420925	eval-logloss:0.426303
[270]	train-logloss:0.420567	eval-logloss:0.42597
[271]	train-logloss:0.420296	eval-logloss:0.425719
[272]	train-logloss:0.419959	eval-logloss:0.425403
[273]	train-logloss:0.419684	eval-logloss:0.425144
[274]	train-logloss:0.419342	eval-logloss:0.424819
[275]	train-logloss:0.419079	eval-logloss:0.424576
[276]	train-logloss:0.418807	eval-logloss:0.424331
[277]	train-logloss:0.418543	eval-logloss:0.424085
[278]	train-logloss:0.418281	eval-logloss:0.423845
[279]	train-logloss:0.417939	eval-logloss:0.423519
[280]	train-logloss:0.417608	eval-logloss:0.423202
[281]	train-logloss:0.417272	eval-logloss:0.422888
[282]	train-logloss:0.417023	eval-logloss:0.422656
[283]	train-logloss:0.416763	eval-logloss:0.422417
[284]	train-logloss:0.416527	eval-logloss:0.422201
[285]	train-logloss:0.416265	eval-logloss:0.421963
[286]	train-logloss:0.415958	eval-logloss:0.421678
[287]	train-logloss:0.415718	eval-logloss:0.421457
[288]	train-logloss:0.415418	eval-logloss:0.421179
[289]	train-logloss:0.415115	eval-logloss:0.4209
[290]	train-logloss:0.414888	eval-logloss:0.420693
[291]	train-logloss:0.414562	eval-logloss:0.420389
[292]	train-logloss:0.414282	eval-logloss:0.420125
[293]	train-logloss:0.414046	eval-logloss:0.419914
[294]	train-logloss:0.413823	eval-logloss:0.419716
[295]	train-logloss:0.413526	eval-logloss:0.419433
[296]	train-logloss:0.413296	eval-logloss:0.41922
[297]	train-logloss:0.412988	eval-logloss:0.418935
[298]	train-logloss:0.412687	eval-logloss:0.418657
[299]	train-logloss:0.412449	eval-logloss:0.418443
[300]	train-logloss:0.412155	eval-logloss:0.418172
[301]	train-logloss:0.411926	eval-logloss:0.417961
[302]	train-logloss:0.411703	eval-logloss:0.41776
[303]	train-logloss:0.411495	eval-logloss:0.417572
[304]	train-logloss:0.411208	eval-logloss:0.417307
[305]	train-logloss:0.410928	eval-logloss:0.417052
[306]	train-logloss:0.410735	eval-logloss:0.416879
[307]	train-logloss:0.41053	eval-logloss:0.41669
[308]	train-logloss:0.410256	eval-logloss:0.416435
[309]	train-logloss:0.410048	eval-logloss:0.416246
[310]	train-logloss:0.409769	eval-logloss:0.415988
[311]	train-logloss:0.409495	eval-logloss:0.415731
[312]	train-logloss:0.409283	eval-logloss:0.415547
[313]	train-logloss:0.40902	eval-logloss:0.415304
[314]	train-logloss:0.408812	eval-logloss:0.415117
[315]	train-logloss:0.408616	eval-logloss:0.414938
[316]	train-logloss:0.408416	eval-logloss:0.414755
[317]	train-logloss:0.40816	eval-logloss:0.414522
[318]	train-logloss:0.407963	eval-logloss:0.414346
[319]	train-logloss:0.407699	eval-logloss:0.414101
[320]	train-logloss:0.407499	eval-logloss:0.413923
[321]	train-logloss:0.407231	eval-logloss:0.413685
[322]	train-logloss:0.406997	eval-logloss:0.413477

[323]	train-logloss:0.4068	eval-logloss:0.413298
[324]	train-logloss:0.406613	eval-logloss:0.413131
[325]	train-logloss:0.406368	eval-logloss:0.412906
[326]	train-logloss:0.406109	eval-logloss:0.412667
[327]	train-logloss:0.405853	eval-logloss:0.412429
[328]	train-logloss:0.405609	eval-logloss:0.412211
[329]	train-logloss:0.405416	eval-logloss:0.412035
[330]	train-logloss:0.405177	eval-logloss:0.411812
[331]	train-logloss:0.405011	eval-logloss:0.411662
[332]	train-logloss:0.404784	eval-logloss:0.411455
[333]	train-logloss:0.404608	eval-logloss:0.411301
[334]	train-logloss:0.404368	eval-logloss:0.411087
[335]	train-logloss:0.40418	eval-logloss:0.410921
[336]	train-logloss:0.403952	eval-logloss:0.410714
[337]	train-logloss:0.403714	eval-logloss:0.410495
[338]	train-logloss:0.40347	eval-logloss:0.410272
[339]	train-logloss:0.403241	eval-logloss:0.410064
[340]	train-logloss:0.403067	eval-logloss:0.409912
[341]	train-logloss:0.402901	eval-logloss:0.409768
[342]	train-logloss:0.402679	eval-logloss:0.409572
[343]	train-logloss:0.402508	eval-logloss:0.409425
[344]	train-logloss:0.402276	eval-logloss:0.409211
[345]	train-logloss:0.402038	eval-logloss:0.408998
[346]	train-logloss:0.40188	eval-logloss:0.408864
[347]	train-logloss:0.401656	eval-logloss:0.408665
[348]	train-logloss:0.40143	eval-logloss:0.408462
[349]	train-logloss:0.401255	eval-logloss:0.408311
[350]	train-logloss:0.40104	eval-logloss:0.408118
[351]	train-logloss:0.40089	eval-logloss:0.407988
[352]	train-logloss:0.400721	eval-logloss:0.407844
[353]	train-logloss:0.400562	eval-logloss:0.407703
[354]	train-logloss:0.400399	eval-logloss:0.407566
[355]	train-logloss:0.400182	eval-logloss:0.40737
[356]	train-logloss:0.399966	eval-logloss:0.407176
[357]	train-logloss:0.399808	eval-logloss:0.40704
[358]	train-logloss:0.399612	eval-logloss:0.406859
[359]	train-logloss:0.39941	eval-logloss:0.406681
[360]	train-logloss:0.399196	eval-logloss:0.406492
[361]	train-logloss:0.398989	eval-logloss:0.406307
[362]	train-logloss:0.398845	eval-logloss:0.406184
[363]	train-logloss:0.398644	eval-logloss:0.406005
[364]	train-logloss:0.398458	eval-logloss:0.405838
[365]	train-logloss:0.398317	eval-logloss:0.405719
[366]	train-logloss:0.398189	eval-logloss:0.405608
[367]	train-logloss:0.397989	eval-logloss:0.405435
[368]	train-logloss:0.397842	eval-logloss:0.40531
[369]	train-logloss:0.397717	eval-logloss:0.405203
[370]	train-logloss:0.397513	eval-logloss:0.40502
[371]	train-logloss:0.397324	eval-logloss:0.404858
[372]	train-logloss:0.397177	eval-logloss:0.404731
[373]	train-logloss:0.397032	eval-logloss:0.404609
[374]	train-logloss:0.396896	eval-logloss:0.404495
[375]	train-logloss:0.396758	eval-logloss:0.40438
[376]	train-logloss:0.39663	eval-logloss:0.404273
[377]	train-logloss:0.396497	eval-logloss:0.404159
[378]	train-logloss:0.396307	eval-logloss:0.403993
[379]	train-logloss:0.396126	eval-logloss:0.403832
[380]	train-logloss:0.395948	eval-logloss:0.403681
[381]	train-logloss:0.395802	eval-logloss:0.403564
[382]	train-logloss:0.395658	eval-logloss:0.403444
[383]	train-logloss:0.395467	eval-logloss:0.403274
[384]	train-logloss:0.395288	eval-logloss:0.403122
[385]	train-logloss:0.395172	eval-logloss:0.403022
[386]	train-logloss:0.394989	eval-logloss:0.402862
[387]	train-logloss:0.394819	eval-logloss:0.402708
[388]	train-logloss:0.394695	eval-logloss:0.402606
[389]	train-logloss:0.394573	eval-logloss:0.40251
[390]	train-logloss:0.394392	eval-logloss:0.402349
[391]	train-logloss:0.394267	eval-logloss:0.402244
[392]	train-logloss:0.394107	eval-logloss:0.402106
[393]	train-logloss:0.393982	eval-logloss:0.402007
[394]	train-logloss:0.393808	eval-logloss:0.401853
[395]	train-logloss:0.393693	eval-logloss:0.401762
[396]	train-logloss:0.393563	eval-logloss:0.401654
[397]	train-logloss:0.393436	eval-logloss:0.401546
[398]	train-logloss:0.393267	eval-logloss:0.401397
[399]	train-logloss:0.39315	eval-logloss:0.401302
[400]	train-logloss:0.392971	eval-logloss:0.401149
[401]	train-logloss:0.392848	eval-logloss:0.401051
[402]	train-logloss:0.392737	eval-logloss:0.400962
[403]	train-logloss:0.39257	eval-logloss:0.400818
[404]	train-logloss:0.392406	eval-logloss:0.400677
[405]	train-logloss:0.392239	eval-logloss:0.400534
[406]	train-logloss:0.392126	eval-logloss:0.400435
[407]	train-logloss:0.391966	eval-logloss:0.4003
[408]	train-logloss:0.391865	eval-logloss:0.400215
[409]	train-logloss:0.391697	eval-logloss:0.400066
[410]	train-logloss:0.391547	eval-logloss:0.399939
[411]	train-logloss:0.391431	eval-logloss:0.399849
[412]	train-logloss:0.39132	eval-logloss:0.399761
[413]	train-logloss:0.391166	eval-logloss:0.399627
[414]	train-logloss:0.391009	eval-logloss:0.399491
[415]	train-logloss:0.390897	eval-logloss:0.399399
[416]	train-logloss:0.390744	eval-logloss:0.399271
[417]	train-logloss:0.390597	eval-logloss:0.399147
[418]	train-logloss:0.390499	eval-logloss:0.399071
[419]	train-logloss:0.390365	eval-logloss:0.398955
[420]	train-logloss:0.390209	eval-logloss:0.398825
[421]	train-logloss:0.390061	eval-logloss:0.398701
[422]	train-logloss:0.389957	eval-logloss:0.398618
[423]	train-logloss:0.38984	eval-logloss:0.398529
[424]	train-logloss:0.389729	eval-logloss:0.398438
[425]	train-logloss:0.389598	eval-logloss:0.398325
[426]	train-logloss:0.389465	eval-logloss:0.398214
[427]	train-logloss:0.389319	eval-logloss:0.398094
[428]	train-logloss:0.389213	eval-logloss:0.398009
[429]	train-logloss:0.389061	eval-logloss:0.397878
[430]	train-logloss:0.388925	eval-logloss:0.39777
[431]	train-logloss:0.388781	eval-logloss:0.397654
[432]	train-logloss:0.388672	eval-logloss:0.397572
[433]	train-logloss:0.388544	eval-logloss:0.397464
[434]	train-logloss:0.388447	eval-logloss:0.397392
[435]	train-logloss:0.388302	eval-logloss:0.397271
[436]	train-logloss:0.388201	eval-logloss:0.397189
[437]	train-logloss:0.388065	eval-logloss:0.397075
[438]	train-logloss:0.387966	eval-logloss:0.396999
[439]	train-logloss:0.387875	eval-logloss:0.396924
[440]	train-logloss:0.387738	eval-logloss:0.396817
[441]	train-logloss:0.38759	eval-logloss:0.396695
[442]	train-logloss:0.387459	eval-logloss:0.396591
[443]	train-logloss:0.387367	eval-logloss:0.396523
[444]	train-logloss:0.387223	eval-logloss:0.396403
[445]	train-logloss:0.387103	eval-logloss:0.396305
[446]	train-logloss:0.387008	eval-logloss:0.396237
[447]	train-logloss:0.386884	eval-logloss:0.396136
[448]	train-logloss:0.386786	eval-logloss:0.396061
[449]	train-logloss:0.386694	eval-logloss:0.395989
[450]	train-logloss:0.386552	eval-logloss:0.395872
[451]	train-logloss:0.386447	eval-logloss:0.395794
[452]	train-logloss:0.386363	eval-logloss:0.395734
[453]	train-logloss:0.38627	eval-logloss:0.395664
[454]	train-logloss:0.386141	eval-logloss:0.395557
[455]	train-logloss:0.38605	eval-logloss:0.395488
[456]	train-logloss:0.385971	eval-logloss:0.395429
[457]	train-logloss:0.38585	eval-logloss:0.395327
[458]	train-logloss:0.385718	eval-logloss:0.395223
[459]	train-logloss:0.385638	eval-logloss:0.395165
[460]	train-logloss:0.385557	eval-logloss:0.395107
[461]	train-logloss:0.385475	eval-logloss:0.395047
[462]	train-logloss:0.385348	eval-logloss:0.394945
[463]	train-logloss:0.385224	eval-logloss:0.394845
[464]	train-logloss:0.385134	eval-logloss:0.394776
[465]	train-logloss:0.385004	eval-logloss:0.394669
[466]	train-logloss:0.38493	eval-logloss:0.394613
[467]	train-logloss:0.384816	eval-logloss:0.394519
[468]	train-logloss:0.384691	eval-logloss:0.394421
[469]	train-logloss:0.384612	eval-logloss:0.394358
[470]	train-logloss:0.384534	eval-logloss:0.394302
[471]	train-logloss:0.384454	eval-logloss:0.394246
[472]	train-logloss:0.384329	eval-logloss:0.394141
[473]	train-logloss:0.384199	eval-logloss:0.394038
[474]	train-logloss:0.384076	eval-logloss:0.393936
[475]	train-logloss:0.383993	eval-logloss:0.39388
[476]	train-logloss:0.383906	eval-logloss:0.393817
[477]	train-logloss:0.383781	eval-logloss:0.393716
[478]	train-logloss:0.383668	eval-logloss:0.393626
[479]	train-logloss:0.383556	eval-logloss:0.393526
[480]	train-logloss:0.383436	eval-logloss:0.393433
[481]	train-logloss:0.383354	eval-logloss:0.393376
[482]	train-logloss:0.383245	eval-logloss:0.393293
[483]	train-logloss:0.38318	eval-logloss:0.393247
[484]	train-logloss:0.38307	eval-logloss:0.393157

[485]	train-logloss:0.382956	eval-logloss:0.393069
[486]	train-logloss:0.382843	eval-logloss:0.392981
[487]	train-logloss:0.38273	eval-logloss:0.392891
[488]	train-logloss:0.382634	eval-logloss:0.392813
[489]	train-logloss:0.382571	eval-logloss:0.392767
[490]	train-logloss:0.382492	eval-logloss:0.39271
[491]	train-logloss:0.382422	eval-logloss:0.39266
[492]	train-logloss:0.382314	eval-logloss:0.392576
[493]	train-logloss:0.382208	eval-logloss:0.392491
[494]	train-logloss:0.382144	eval-logloss:0.39245
[495]	train-logloss:0.382077	eval-logloss:0.392401
[496]	train-logloss:0.381979	eval-logloss:0.392323
[497]	train-logloss:0.381916	eval-logloss:0.39228
[498]	train-logloss:0.381813	eval-logloss:0.392198
[499]	train-logloss:0.381744	eval-logloss:0.392146
[500]	train-logloss:0.381645	eval-logloss:0.392065
[501]	train-logloss:0.381568	eval-logloss:0.392014
[502]	train-logloss:0.381455	eval-logloss:0.391928
[503]	train-logloss:0.381361	eval-logloss:0.391859
[504]	train-logloss:0.381288	eval-logloss:0.391809
[505]	train-logloss:0.381212	eval-logloss:0.391758
[506]	train-logloss:0.381148	eval-logloss:0.391717
[507]	train-logloss:0.381069	eval-logloss:0.391665
[508]	train-logloss:0.380996	eval-logloss:0.391613
[509]	train-logloss:0.380936	eval-logloss:0.391579
[510]	train-logloss:0.380831	eval-logloss:0.3915
[511]	train-logloss:0.380758	eval-logloss:0.391454
[512]	train-logloss:0.380644	eval-logloss:0.391365
[513]	train-logloss:0.380547	eval-logloss:0.39129
[514]	train-logloss:0.380482	eval-logloss:0.391247
[515]	train-logloss:0.380376	eval-logloss:0.391161
[516]	train-logloss:0.380309	eval-logloss:0.391113
[517]	train-logloss:0.38022	eval-logloss:0.391045
[518]	train-logloss:0.380162	eval-logloss:0.391001
[519]	train-logloss:0.380104	eval-logloss:0.390964
[520]	train-logloss:0.38003	eval-logloss:0.390917
[521]	train-logloss:0.379972	eval-logloss:0.39088
[522]	train-logloss:0.379908	eval-logloss:0.390835
[523]	train-logloss:0.379807	eval-logloss:0.390756
[524]	train-logloss:0.379745	eval-logloss:0.390718
[525]	train-logloss:0.379687	eval-logloss:0.390678
[526]	train-logloss:0.379631	eval-logloss:0.390642
[527]	train-logloss:0.379548	eval-logloss:0.39058
[528]	train-logloss:0.379484	eval-logloss:0.390539
[529]	train-logloss:0.379385	eval-logloss:0.390467
[530]	train-logloss:0.379328	eval-logloss:0.390436
[531]	train-logloss:0.379235	eval-logloss:0.390363
[532]	train-logloss:0.37913	eval-logloss:0.390282
[533]	train-logloss:0.379029	eval-logloss:0.390205
[534]	train-logloss:0.37894	eval-logloss:0.390139
[535]	train-logloss:0.378849	eval-logloss:0.390072
[536]	train-logloss:0.37876	eval-logloss:0.390011
[537]	train-logloss:0.378705	eval-logloss:0.389981
[538]	train-logloss:0.378646	eval-logloss:0.389948
[539]	train-logloss:0.378592	eval-logloss:0.389922
[540]	train-logloss:0.378503	eval-logloss:0.389849
[541]	train-logloss:0.378416	eval-logloss:0.389781
[542]	train-logloss:0.378336	eval-logloss:0.389724
[543]	train-logloss:0.378244	eval-logloss:0.389661
[544]	train-logloss:0.378183	eval-logloss:0.389623
[545]	train-logloss:0.378092	eval-logloss:0.389554
[546]	train-logloss:0.378028	eval-logloss:0.389513
[547]	train-logloss:0.37797	eval-logloss:0.389476
[548]	train-logloss:0.377919	eval-logloss:0.389447
[549]	train-logloss:0.377832	eval-logloss:0.389383
[550]	train-logloss:0.377773	eval-logloss:0.389347
[551]	train-logloss:0.377691	eval-logloss:0.389282
[552]	train-logloss:0.377604	eval-logloss:0.389214
[553]	train-logloss:0.377516	eval-logloss:0.389148
[554]	train-logloss:0.377429	eval-logloss:0.389085
[555]	train-logloss:0.377369	eval-logloss:0.389047
[556]	train-logloss:0.377316	eval-logloss:0.389017
[557]	train-logloss:0.377233	eval-logloss:0.388958
[558]	train-logloss:0.377147	eval-logloss:0.388894
[559]	train-logloss:0.377095	eval-logloss:0.388865
[560]	train-logloss:0.377044	eval-logloss:0.388833
[561]	train-logloss:0.376992	eval-logloss:0.3888
[562]	train-logloss:0.376915	eval-logloss:0.388745
[563]	train-logloss:0.376863	eval-logloss:0.388714
[564]	train-logloss:0.37681	eval-logloss:0.388687
[565]	train-logloss:0.376734	eval-logloss:0.388635
[566]	train-logloss:0.376678	eval-logloss:0.388602
[567]	train-logloss:0.3766	eval-logloss:0.388546
[568]	train-logloss:0.376512	eval-logloss:0.388482
[569]	train-logloss:0.376419	eval-logloss:0.38841
[570]	train-logloss:0.376348	eval-logloss:0.38836
[571]	train-logloss:0.376263	eval-logloss:0.388299
[572]	train-logloss:0.376176	eval-logloss:0.38824
[573]	train-logloss:0.37612	eval-logloss:0.388206
[574]	train-logloss:0.376072	eval-logloss:0.388179
[575]	train-logloss:0.375991	eval-logloss:0.388122
[576]	train-logloss:0.375913	eval-logloss:0.388066
[577]	train-logloss:0.375865	eval-logloss:0.388046
[578]	train-logloss:0.375807	eval-logloss:0.388014
[579]	train-logloss:0.375757	eval-logloss:0.387991
[580]	train-logloss:0.375687	eval-logloss:0.387941
[581]	train-logloss:0.375611	eval-logloss:0.387885
[582]	train-logloss:0.37556	eval-logloss:0.387858
[583]	train-logloss:0.375511	eval-logloss:0.387831
[584]	train-logloss:0.37546	eval-logloss:0.387809
[585]	train-logloss:0.37541	eval-logloss:0.387777
[586]	train-logloss:0.375367	eval-logloss:0.387752
[587]	train-logloss:0.375315	eval-logloss:0.387727
[588]	train-logloss:0.375264	eval-logloss:0.387692
[589]	train-logloss:0.375216	eval-logloss:0.38767
[590]	train-logloss:0.375132	eval-logloss:0.387608
[591]	train-logloss:0.375082	eval-logloss:0.38758
[592]	train-logloss:0.374997	eval-logloss:0.387525
[593]	train-logloss:0.374946	eval-logloss:0.387493
[594]	train-logloss:0.374896	eval-logloss:0.387462
[595]	train-logloss:0.374818	eval-logloss:0.387406
[596]	train-logloss:0.374751	eval-logloss:0.387362
[597]	train-logloss:0.374704	eval-logloss:0.387338
[598]	train-logloss:0.374633	eval-logloss:0.387293
[599]	train-logloss:0.374558	eval-logloss:0.387238
[600]	train-logloss:0.374491	eval-logloss:0.38719
[601]	train-logloss:0.37442	eval-logloss:0.387143
[602]	train-logloss:0.374341	eval-logloss:0.387089
[603]	train-logloss:0.37428	eval-logloss:0.387053
[604]	train-logloss:0.374228	eval-logloss:0.387025
[605]	train-logloss:0.374174	eval-logloss:0.386998
[606]	train-logloss:0.374101	eval-logloss:0.386951
[607]	train-logloss:0.374057	eval-logloss:0.386928
[608]	train-logloss:0.374009	eval-logloss:0.386907
[609]	train-logloss:0.373962	eval-logloss:0.386885
[610]	train-logloss:0.373918	eval-logloss:0.386864
[611]	train-logloss:0.373872	eval-logloss:0.386844
[612]	train-logloss:0.373801	eval-logloss:0.386796
[613]	train-logloss:0.373752	eval-logloss:0.386773
[614]	train-logloss:0.373709	eval-logloss:0.386749
[615]	train-logloss:0.373642	eval-logloss:0.386704
[616]	train-logloss:0.373598	eval-logloss:0.386681
[617]	train-logloss:0.373528	eval-logloss:0.386636
[618]	train-logloss:0.373463	eval-logloss:0.386591
[619]	train-logloss:0.373396	eval-logloss:0.386548
[620]	train-logloss:0.373333	eval-logloss:0.386504
[621]	train-logloss:0.373291	eval-logloss:0.386479
[622]	train-logloss:0.373243	eval-logloss:0.386456
[623]	train-logloss:0.373166	eval-logloss:0.386404
[624]	train-logloss:0.373125	eval-logloss:0.386387
[625]	train-logloss:0.373048	eval-logloss:0.38633
[626]	train-logloss:0.372983	eval-logloss:0.386295
[627]	train-logloss:0.372923	eval-logloss:0.386258
[628]	train-logloss:0.372863	eval-logloss:0.386218
[629]	train-logloss:0.37279	eval-logloss:0.386171
[630]	train-logloss:0.372724	eval-logloss:0.386127
[631]	train-logloss:0.372653	eval-logloss:0.386086
[632]	train-logloss:0.372594	eval-logloss:0.386049
[633]	train-logloss:0.372531	eval-logloss:0.386006
[634]	train-logloss:0.372462	eval-logloss:0.385966
[635]	train-logloss:0.372399	eval-logloss:0.38592
[636]	train-logloss:0.37235	eval-logloss:0.385894
[637]	train-logloss:0.372306	eval-logloss:0.385872
[638]	train-logloss:0.372233	eval-logloss:0.385821
[639]	train-logloss:0.372162	eval-logloss:0.38577
[640]	train-logloss:0.372115	eval-logloss:0.385743
[641]	train-logloss:0.372076	eval-logloss:0.385724
[642]	train-logloss:0.372018	eval-logloss:0.385685
[643]	train-logloss:0.371978	eval-logloss:0.385662
[644]	train-logloss:0.37191	eval-logloss:0.385615
[645]	train-logloss:0.371851	eval-logloss:0.385579
[646]	train-logloss:0.371811	eval-logloss:0.385562

[647]	train-logloss:0.371755	eval-logloss:0.38552
[648]	train-logloss:0.371692	eval-logloss:0.385485
[649]	train-logloss:0.371647	eval-logloss:0.385466
[650]	train-logloss:0.371607	eval-logloss:0.385447
[651]	train-logloss:0.371562	eval-logloss:0.385423
[652]	train-logloss:0.371517	eval-logloss:0.385405
[653]	train-logloss:0.37146	eval-logloss:0.385366
[654]	train-logloss:0.371431	eval-logloss:0.385348
[655]	train-logloss:0.371392	eval-logloss:0.385329
[656]	train-logloss:0.371355	eval-logloss:0.385314
[657]	train-logloss:0.371318	eval-logloss:0.385297
[658]	train-logloss:0.371256	eval-logloss:0.385256
[659]	train-logloss:0.371201	eval-logloss:0.385216
[660]	train-logloss:0.371137	eval-logloss:0.38518
[661]	train-logloss:0.371095	eval-logloss:0.385158
[662]	train-logloss:0.371051	eval-logloss:0.385136
[663]	train-logloss:0.371012	eval-logloss:0.385116
[664]	train-logloss:0.370953	eval-logloss:0.385084
[665]	train-logloss:0.370888	eval-logloss:0.385046
[666]	train-logloss:0.370825	eval-logloss:0.385008
[667]	train-logloss:0.37078	eval-logloss:0.384984
[668]	train-logloss:0.370745	eval-logloss:0.384968
[669]	train-logloss:0.370684	eval-logloss:0.384931
[670]	train-logloss:0.370622	eval-logloss:0.384893
[671]	train-logloss:0.37058	eval-logloss:0.38487
[672]	train-logloss:0.370534	eval-logloss:0.384851
[673]	train-logloss:0.37048	eval-logloss:0.384819
[674]	train-logloss:0.370442	eval-logloss:0.384805
[675]	train-logloss:0.370379	eval-logloss:0.384762
[676]	train-logloss:0.370318	eval-logloss:0.384726
[677]	train-logloss:0.370257	eval-logloss:0.384693
[678]	train-logloss:0.370199	eval-logloss:0.384656
[679]	train-logloss:0.370161	eval-logloss:0.384642
[680]	train-logloss:0.370107	eval-logloss:0.384608
[681]	train-logloss:0.370073	eval-logloss:0.384594
[682]	train-logloss:0.370041	eval-logloss:0.384577
[683]	train-logloss:0.369985	eval-logloss:0.384545
[684]	train-logloss:0.369921	eval-logloss:0.384511
[685]	train-logloss:0.369864	eval-logloss:0.384476
[686]	train-logloss:0.369834	eval-logloss:0.384466
[687]	train-logloss:0.369802	eval-logloss:0.384452
[688]	train-logloss:0.36975	eval-logloss:0.384424
[689]	train-logloss:0.369698	eval-logloss:0.384395
[690]	train-logloss:0.369667	eval-logloss:0.38438
[691]	train-logloss:0.369633	eval-logloss:0.384369
[692]	train-logloss:0.369572	eval-logloss:0.384333
[693]	train-logloss:0.369511	eval-logloss:0.3843
[694]	train-logloss:0.369452	eval-logloss:0.38426
[695]	train-logloss:0.369402	eval-logloss:0.384233
[696]	train-logloss:0.36937	eval-logloss:0.384217
[697]	train-logloss:0.36932	eval-logloss:0.384189
[698]	train-logloss:0.369263	eval-logloss:0.38416
[699]	train-logloss:0.369208	eval-logloss:0.384127
[700]	train-logloss:0.369156	eval-logloss:0.384102
[701]	train-logloss:0.369127	eval-logloss:0.384091
[702]	train-logloss:0.369074	eval-logloss:0.384068
[703]	train-logloss:0.36904	eval-logloss:0.384054
[704]	train-logloss:0.368986	eval-logloss:0.384023
[705]	train-logloss:0.368931	eval-logloss:0.383991
[706]	train-logloss:0.368907	eval-logloss:0.383978
[707]	train-logloss:0.368849	eval-logloss:0.383945
[708]	train-logloss:0.368796	eval-logloss:0.383918
[709]	train-logloss:0.368758	eval-logloss:0.383905
[710]	train-logloss:0.368705	eval-logloss:0.383879
[711]	train-logloss:0.36865	eval-logloss:0.38385
[712]	train-logloss:0.368596	eval-logloss:0.383816
[713]	train-logloss:0.368558	eval-logloss:0.383801
[714]	train-logloss:0.368509	eval-logloss:0.383772
[715]	train-logloss:0.368483	eval-logloss:0.383763
[716]	train-logloss:0.368429	eval-logloss:0.38373
[717]	train-logloss:0.368394	eval-logloss:0.383714
[718]	train-logloss:0.368357	eval-logloss:0.383701
[719]	train-logloss:0.36832	eval-logloss:0.383683
[720]	train-logloss:0.368265	eval-logloss:0.383658
[721]	train-logloss:0.368225	eval-logloss:0.383642
[722]	train-logloss:0.36819	eval-logloss:0.383625
[723]	train-logloss:0.368142	eval-logloss:0.383591
[724]	train-logloss:0.368105	eval-logloss:0.383579
[725]	train-logloss:0.368078	eval-logloss:0.383568
[726]	train-logloss:0.368038	eval-logloss:0.383547
[727]	train-logloss:0.368002	eval-logloss:0.383531
[728]	train-logloss:0.367963	eval-logloss:0.383521
[729]	train-logloss:0.367909	eval-logloss:0.383491
[730]	train-logloss:0.367853	eval-logloss:0.383458
[731]	train-logloss:0.367804	eval-logloss:0.383434
[732]	train-logloss:0.367765	eval-logloss:0.383421
[733]	train-logloss:0.367722	eval-logloss:0.383404
[734]	train-logloss:0.367693	eval-logloss:0.383391
[735]	train-logloss:0.367643	eval-logloss:0.383369
[736]	train-logloss:0.367605	eval-logloss:0.383355
[737]	train-logloss:0.367555	eval-logloss:0.383335
[738]	train-logloss:0.367502	eval-logloss:0.383303
[739]	train-logloss:0.367478	eval-logloss:0.383292
[740]	train-logloss:0.367446	eval-logloss:0.38328
[741]	train-logloss:0.3674	eval-logloss:0.383256
[742]	train-logloss:0.367372	eval-logloss:0.38325
[743]	train-logloss:0.367331	eval-logloss:0.383229
[744]	train-logloss:0.367295	eval-logloss:0.383223
[745]	train-logloss:0.367263	eval-logloss:0.383215
[746]	train-logloss:0.367236	eval-logloss:0.383205
[747]	train-logloss:0.367192	eval-logloss:0.383181
[748]	train-logloss:0.367141	eval-logloss:0.383156
[749]	train-logloss:0.36709	eval-logloss:0.38313
[750]	train-logloss:0.367042	eval-logloss:0.383104
[751]	train-logloss:0.366992	eval-logloss:0.383082
[752]	train-logloss:0.366945	eval-logloss:0.383057
[753]	train-logloss:0.366911	eval-logloss:0.383047
[754]	train-logloss:0.366886	eval-logloss:0.383039
[755]	train-logloss:0.36683	eval-logloss:0.38301
[756]	train-logloss:0.366784	eval-logloss:0.382987
[757]	train-logloss:0.366747	eval-logloss:0.382973
[758]	train-logloss:0.36672	eval-logloss:0.382961
[759]	train-logloss:0.366674	eval-logloss:0.382935
[760]	train-logloss:0.366623	eval-logloss:0.382907
[761]	train-logloss:0.366599	eval-logloss:0.3829
[762]	train-logloss:0.366553	eval-logloss:0.382875
[763]	train-logloss:0.366508	eval-logloss:0.382852
[764]	train-logloss:0.366475	eval-logloss:0.38284
[765]	train-logloss:0.366443	eval-logloss:0.382825
[766]	train-logloss:0.366394	eval-logloss:0.382796
[767]	train-logloss:0.366359	eval-logloss:0.382782
[768]	train-logloss:0.366307	eval-logloss:0.382755
[769]	train-logloss:0.366274	eval-logloss:0.382742
[770]	train-logloss:0.366244	eval-logloss:0.382733
[771]	train-logloss:0.36622	eval-logloss:0.382723
[772]	train-logloss:0.366167	eval-logloss:0.382699
[773]	train-logloss:0.366133	eval-logloss:0.382686
[774]	train-logloss:0.36609	eval-logloss:0.382665
[775]	train-logloss:0.366048	eval-logloss:0.38265
[776]	train-logloss:0.366005	eval-logloss:0.382625
[777]	train-logloss:0.365972	eval-logloss:0.382617
[778]	train-logloss:0.365924	eval-logloss:0.382588
[779]	train-logloss:0.365877	eval-logloss:0.382566
[780]	train-logloss:0.365841	eval-logloss:0.382556
[781]	train-logloss:0.365815	eval-logloss:0.382547
[782]	train-logloss:0.365781	eval-logloss:0.382536
[783]	train-logloss:0.365736	eval-logloss:0.382511
[784]	train-logloss:0.365705	eval-logloss:0.382498
[785]	train-logloss:0.365668	eval-logloss:0.382485
[786]	train-logloss:0.365619	eval-logloss:0.38246
[787]	train-logloss:0.365583	eval-logloss:0.382451
[788]	train-logloss:0.365549	eval-logloss:0.382441
[789]	train-logloss:0.365519	eval-logloss:0.382431
[790]	train-logloss:0.365486	eval-logloss:0.382422
[791]	train-logloss:0.365438	eval-logloss:0.382396
[792]	train-logloss:0.365406	eval-logloss:0.382385
[793]	train-logloss:0.365375	eval-logloss:0.382374
[794]	train-logloss:0.365339	eval-logloss:0.382364
[795]	train-logloss:0.365293	eval-logloss:0.382341
[796]	train-logloss:0.365256	eval-logloss:0.382333
[797]	train-logloss:0.365206	eval-logloss:0.38231
[798]	train-logloss:0.365177	eval-logloss:0.3823
[799]	train-logloss:0.365137	eval-logloss:0.382293
[800]	train-logloss:0.365098	eval-logloss:0.382276
[801]	train-logloss:0.365067	eval-logloss:0.382266
[802]	train-logloss:0.365019	eval-logloss:0.382247
[803]	train-logloss:0.364994	eval-logloss:0.382237
[804]	train-logloss:0.36496	eval-logloss:0.382227
[805]	train-logloss:0.364935	eval-logloss:0.38222
[806]	train-logloss:0.364894	eval-logloss:0.382197
[807]	train-logloss:0.364862	eval-logloss:0.382186
[808]	train-logloss:0.364827	eval-logloss:0.382172

[809]	train-logloss:0.364779	eval-logloss:0.382156
[810]	train-logloss:0.364749	eval-logloss:0.382148
[811]	train-logloss:0.364722	eval-logloss:0.382137
[812]	train-logloss:0.364676	eval-logloss:0.382115
[813]	train-logloss:0.364635	eval-logloss:0.382097
[814]	train-logloss:0.364587	eval-logloss:0.382071
[815]	train-logloss:0.364543	eval-logloss:0.38205
[816]	train-logloss:0.364516	eval-logloss:0.382042
[817]	train-logloss:0.364473	eval-logloss:0.382021
[818]	train-logloss:0.364435	eval-logloss:0.382003
[819]	train-logloss:0.364399	eval-logloss:0.381995
[820]	train-logloss:0.36436	eval-logloss:0.381979
[821]	train-logloss:0.36433	eval-logloss:0.38197
[822]	train-logloss:0.364289	eval-logloss:0.381948
[823]	train-logloss:0.364249	eval-logloss:0.381931
[824]	train-logloss:0.364221	eval-logloss:0.381922
[825]	train-logloss:0.364184	eval-logloss:0.381902
[826]	train-logloss:0.36415	eval-logloss:0.381894
[827]	train-logloss:0.364124	eval-logloss:0.381886
[828]	train-logloss:0.364083	eval-logloss:0.381862
[829]	train-logloss:0.364051	eval-logloss:0.381854
[830]	train-logloss:0.364017	eval-logloss:0.381839
[831]	train-logloss:0.363989	eval-logloss:0.38183
[832]	train-logloss:0.363954	eval-logloss:0.381817
[833]	train-logloss:0.363923	eval-logloss:0.381809
[834]	train-logloss:0.363892	eval-logloss:0.381805
[835]	train-logloss:0.363849	eval-logloss:0.381788
[836]	train-logloss:0.363812	eval-logloss:0.38177
[837]	train-logloss:0.363787	eval-logloss:0.381762
[838]	train-logloss:0.36376	eval-logloss:0.381758
[839]	train-logloss:0.363725	eval-logloss:0.381745
[840]	train-logloss:0.363694	eval-logloss:0.38174
[841]	train-logloss:0.363657	eval-logloss:0.381733
[842]	train-logloss:0.363619	eval-logloss:0.381717
[843]	train-logloss:0.363577	eval-logloss:0.381704
[844]	train-logloss:0.363538	eval-logloss:0.381689
[845]	train-logloss:0.3635	eval-logloss:0.38167
[846]	train-logloss:0.363461	eval-logloss:0.381657
[847]	train-logloss:0.363416	eval-logloss:0.38164
[848]	train-logloss:0.363378	eval-logloss:0.381626
[849]	train-logloss:0.363345	eval-logloss:0.381614
[850]	train-logloss:0.363309	eval-logloss:0.381594
[851]	train-logloss:0.36328	eval-logloss:0.38159
[852]	train-logloss:0.363257	eval-logloss:0.381585
[853]	train-logloss:0.363231	eval-logloss:0.381578
[854]	train-logloss:0.363192	eval-logloss:0.381559
[855]	train-logloss:0.363165	eval-logloss:0.381552
[856]	train-logloss:0.363131	eval-logloss:0.381541
[857]	train-logloss:0.363102	eval-logloss:0.381537
[858]	train-logloss:0.36307	eval-logloss:0.381522
[859]	train-logloss:0.363043	eval-logloss:0.381513
[860]	train-logloss:0.363005	eval-logloss:0.381498
[861]	train-logloss:0.362978	eval-logloss:0.38149
[862]	train-logloss:0.362937	eval-logloss:0.381472
[863]	train-logloss:0.362895	eval-logloss:0.381453
[864]	train-logloss:0.362859	eval-logloss:0.381441
[865]	train-logloss:0.362827	eval-logloss:0.381435
[866]	train-logloss:0.362799	eval-logloss:0.381428
[867]	train-logloss:0.362763	eval-logloss:0.381416
[868]	train-logloss:0.362726	eval-logloss:0.381403
[869]	train-logloss:0.362691	eval-logloss:0.381391
[870]	train-logloss:0.362649	eval-logloss:0.381376
[871]	train-logloss:0.362613	eval-logloss:0.381366
[872]	train-logloss:0.362585	eval-logloss:0.381355
[873]	train-logloss:0.362558	eval-logloss:0.381353
[874]	train-logloss:0.362541	eval-logloss:0.381349
[875]	train-logloss:0.3625	eval-logloss:0.381331
[876]	train-logloss:0.362464	eval-logloss:0.381319
[877]	train-logloss:0.362437	eval-logloss:0.381311
[878]	train-logloss:0.362401	eval-logloss:0.381293
[879]	train-logloss:0.362363	eval-logloss:0.381279
[880]	train-logloss:0.362321	eval-logloss:0.381265
[881]	train-logloss:0.362283	eval-logloss:0.381253
[882]	train-logloss:0.362254	eval-logloss:0.381246
[883]	train-logloss:0.362208	eval-logloss:0.381228
[884]	train-logloss:0.362175	eval-logloss:0.381212
[885]	train-logloss:0.362132	eval-logloss:0.381196
[886]	train-logloss:0.362103	eval-logloss:0.381187
[887]	train-logloss:0.362073	eval-logloss:0.381181
[888]	train-logloss:0.362045	eval-logloss:0.38118
[889]	train-logloss:0.362014	eval-logloss:0.381168
[890]	train-logloss:0.361985	eval-logloss:0.381162
[891]	train-logloss:0.361957	eval-logloss:0.381154
[892]	train-logloss:0.361933	eval-logloss:0.381147
[893]	train-logloss:0.361912	eval-logloss:0.381138
[894]	train-logloss:0.361876	eval-logloss:0.381123
[895]	train-logloss:0.361846	eval-logloss:0.381119
[896]	train-logloss:0.361809	eval-logloss:0.381105
[897]	train-logloss:0.361779	eval-logloss:0.381089
[898]	train-logloss:0.361756	eval-logloss:0.381084
[899]	train-logloss:0.361726	eval-logloss:0.381079
[900]	train-logloss:0.361691	eval-logloss:0.381064
[901]	train-logloss:0.361663	eval-logloss:0.381058
[902]	train-logloss:0.361636	eval-logloss:0.381052
[903]	train-logloss:0.361597	eval-logloss:0.381034
[904]	train-logloss:0.361561	eval-logloss:0.381019
[905]	train-logloss:0.361534	eval-logloss:0.381015
[906]	train-logloss:0.361498	eval-logloss:0.380997
[907]	train-logloss:0.361466	eval-logloss:0.38099
[908]	train-logloss:0.36143	eval-logloss:0.380975
[909]	train-logloss:0.361401	eval-logloss:0.380966
[910]	train-logloss:0.36137	eval-logloss:0.380959
[911]	train-logloss:0.361333	eval-logloss:0.380946
[912]	train-logloss:0.361297	eval-logloss:0.380931
[913]	train-logloss:0.361259	eval-logloss:0.380918
[914]	train-logloss:0.361222	eval-logloss:0.380899
[915]	train-logloss:0.361193	eval-logloss:0.380893
[916]	train-logloss:0.361162	eval-logloss:0.380886
[917]	train-logloss:0.361121	eval-logloss:0.380872
[918]	train-logloss:0.361096	eval-logloss:0.380867
[919]	train-logloss:0.361068	eval-logloss:0.380863
[920]	train-logloss:0.361029	eval-logloss:0.380854
[921]	train-logloss:0.360994	eval-logloss:0.380839
[922]	train-logloss:0.360971	eval-logloss:0.380833
[923]	train-logloss:0.360941	eval-logloss:0.380823
[924]	train-logloss:0.360913	eval-logloss:0.380812
[925]	train-logloss:0.360878	eval-logloss:0.3808
[926]	train-logloss:0.36085	eval-logloss:0.380792
[927]	train-logloss:0.360816	eval-logloss:0.380778
[928]	train-logloss:0.36079	eval-logloss:0.380772
[929]	train-logloss:0.360764	eval-logloss:0.380766
[930]	train-logloss:0.360733	eval-logloss:0.380764
[931]	train-logloss:0.360701	eval-logloss:0.380752
[932]	train-logloss:0.36068	eval-logloss:0.380747
[933]	train-logloss:0.360648	eval-logloss:0.380739
[934]	train-logloss:0.360611	eval-logloss:0.380728
[935]	train-logloss:0.36058	eval-logloss:0.380725
[936]	train-logloss:0.360543	eval-logloss:0.38071
[937]	train-logloss:0.360517	eval-logloss:0.380708
[938]	train-logloss:0.360483	eval-logloss:0.380697
[939]	train-logloss:0.360467	eval-logloss:0.380691
[940]	train-logloss:0.360432	eval-logloss:0.38068
[941]	train-logloss:0.360412	eval-logloss:0.380676
[942]	train-logloss:0.360383	eval-logloss:0.380673
[943]	train-logloss:0.360357	eval-logloss:0.380664
[944]	train-logloss:0.36033	eval-logloss:0.380664
[945]	train-logloss:0.360294	eval-logloss:0.380651
[946]	train-logloss:0.360254	eval-logloss:0.380638
[947]	train-logloss:0.360223	eval-logloss:0.380632
[948]	train-logloss:0.36019	eval-logloss:0.38062
[949]	train-logloss:0.360166	eval-logloss:0.380618
[950]	train-logloss:0.360132	eval-logloss:0.380609
[951]	train-logloss:0.360103	eval-logloss:0.380605
[952]	train-logloss:0.36007	eval-logloss:0.380599
[953]	train-logloss:0.360047	eval-logloss:0.380595
[954]	train-logloss:0.360017	eval-logloss:0.380592
[955]	train-logloss:0.359982	eval-logloss:0.380577
[956]	train-logloss:0.359959	eval-logloss:0.38057
[957]	train-logloss:0.359928	eval-logloss:0.38057
[958]	train-logloss:0.359892	eval-logloss:0.38056
[959]	train-logloss:0.359878	eval-logloss:0.380555
[960]	train-logloss:0.359846	eval-logloss:0.380547
[961]	train-logloss:0.359811	eval-logloss:0.380533
[962]	train-logloss:0.359784	eval-logloss:0.380528
[963]	train-logloss:0.35975	eval-logloss:0.380521
[964]	train-logloss:0.359718	eval-logloss:0.380511
[965]	train-logloss:0.359694	eval-logloss:0.380506
[966]	train-logloss:0.359661	eval-logloss:0.380495
[967]	train-logloss:0.359628	eval-logloss:0.380486
[968]	train-logloss:0.359599	eval-logloss:0.380483
[969]	train-logloss:0.359568	eval-logloss:0.380476
[970]	train-logloss:0.359538	eval-logloss:0.380465

[971]	train-logloss:0.359508	eval-logloss:0.380455
[972]	train-logloss:0.359481	eval-logloss:0.380447
[973]	train-logloss:0.359447	eval-logloss:0.380434
[974]	train-logloss:0.359416	eval-logloss:0.380426
[975]	train-logloss:0.359384	eval-logloss:0.380414
[976]	train-logloss:0.359353	eval-logloss:0.380402
[977]	train-logloss:0.359321	eval-logloss:0.380393
[978]	train-logloss:0.359297	eval-logloss:0.380397
[979]	train-logloss:0.359275	eval-logloss:0.380392
[980]	train-logloss:0.359251	eval-logloss:0.380392
[981]	train-logloss:0.359216	eval-logloss:0.380384
[982]	train-logloss:0.359193	eval-logloss:0.38038
[983]	train-logloss:0.359166	eval-logloss:0.380368
[984]	train-logloss:0.35913	eval-logloss:0.380358
[985]	train-logloss:0.359099	eval-logloss:0.380348
[986]	train-logloss:0.359075	eval-logloss:0.380344
[987]	train-logloss:0.359049	eval-logloss:0.380334
[988]	train-logloss:0.359027	eval-logloss:0.380326
[989]	train-logloss:0.359003	eval-logloss:0.380323
[990]	train-logloss:0.358971	eval-logloss:0.380312
[991]	train-logloss:0.358947	eval-logloss:0.380309
[992]	train-logloss:0.358921	eval-logloss:0.3803
[993]	train-logloss:0.358884	eval-logloss:0.380288
[994]	train-logloss:0.358849	eval-logloss:0.380278
[995]	train-logloss:0.358821	eval-logloss:0.38027
[996]	train-logloss:0.358803	eval-logloss:0.380265
[997]	train-logloss:0.35877	eval-logloss:0.38025
[998]	train-logloss:0.358741	eval-logloss:0.380245
[999]	train-logloss:0.358715	eval-logloss:0.380242
[1000]	train-logloss:0.358694	eval-logloss:0.38024
[1001]	train-logloss:0.358665	eval-logloss:0.380236
[1002]	train-logloss:0.358637	eval-logloss:0.380233
[1003]	train-logloss:0.358617	eval-logloss:0.380228
[1004]	train-logloss:0.358585	eval-logloss:0.380219
[1005]	train-logloss:0.358554	eval-logloss:0.380208
[1006]	train-logloss:0.358528	eval-logloss:0.380207
[1007]	train-logloss:0.358504	eval-logloss:0.380205
[1008]	train-logloss:0.358487	eval-logloss:0.380201
[1009]	train-logloss:0.358454	eval-logloss:0.380189
[1010]	train-logloss:0.358425	eval-logloss:0.380178
[1011]	train-logloss:0.35839	eval-logloss:0.380163
[1012]	train-logloss:0.358364	eval-logloss:0.380157
[1013]	train-logloss:0.358331	eval-logloss:0.380145
[1014]	train-logloss:0.35831	eval-logloss:0.380139
[1015]	train-logloss:0.35829	eval-logloss:0.380136
[1016]	train-logloss:0.35826	eval-logloss:0.380127
[1017]	train-logloss:0.358237	eval-logloss:0.380122
[1018]	train-logloss:0.358207	eval-logloss:0.380118
[1019]	train-logloss:0.358177	eval-logloss:0.380111
[1020]	train-logloss:0.358153	eval-logloss:0.380108
[1021]	train-logloss:0.35813	eval-logloss:0.380104
[1022]	train-logloss:0.358099	eval-logloss:0.380096
[1023]	train-logloss:0.358072	eval-logloss:0.380093
[1024]	train-logloss:0.358043	eval-logloss:0.380084
[1025]	train-logloss:0.358015	eval-logloss:0.380075
[1026]	train-logloss:0.357992	eval-logloss:0.380067
[1027]	train-logloss:0.357963	eval-logloss:0.380063
[1028]	train-logloss:0.35793	eval-logloss:0.380058
[1029]	train-logloss:0.357894	eval-logloss:0.380052
[1030]	train-logloss:0.35787	eval-logloss:0.38005
[1031]	train-logloss:0.357841	eval-logloss:0.380041
[1032]	train-logloss:0.357816	eval-logloss:0.380034
[1033]	train-logloss:0.357791	eval-logloss:0.38003
[1034]	train-logloss:0.357761	eval-logloss:0.380023
[1035]	train-logloss:0.357735	eval-logloss:0.380018
[1036]	train-logloss:0.357704	eval-logloss:0.380014
[1037]	train-logloss:0.357687	eval-logloss:0.380009
[1038]	train-logloss:0.357665	eval-logloss:0.380003
[1039]	train-logloss:0.357651	eval-logloss:0.379999
[1040]	train-logloss:0.357622	eval-logloss:0.379989
[1041]	train-logloss:0.357592	eval-logloss:0.379982
[1042]	train-logloss:0.357566	eval-logloss:0.379976
[1043]	train-logloss:0.35754	eval-logloss:0.379976
[1044]	train-logloss:0.35752	eval-logloss:0.379969
[1045]	train-logloss:0.357498	eval-logloss:0.379967
[1046]	train-logloss:0.357473	eval-logloss:0.379958
[1047]	train-logloss:0.357446	eval-logloss:0.379954
[1048]	train-logloss:0.357417	eval-logloss:0.379948
[1049]	train-logloss:0.35738	eval-logloss:0.379941
[1050]	train-logloss:0.35736	eval-logloss:0.379935
[1051]	train-logloss:0.357337	eval-logloss:0.379933
[1052]	train-logloss:0.357314	eval-logloss:0.379931
[1053]	train-logloss:0.357285	eval-logloss:0.379932
[1054]	train-logloss:0.357267	eval-logloss:0.379929
[1055]	train-logloss:0.357232	eval-logloss:0.379924
[1056]	train-logloss:0.357205	eval-logloss:0.379916
[1057]	train-logloss:0.357172	eval-logloss:0.379907
[1058]	train-logloss:0.35715	eval-logloss:0.379905
[1059]	train-logloss:0.35713	eval-logloss:0.379905
[1060]	train-logloss:0.357099	eval-logloss:0.379892
[1061]	train-logloss:0.35707	eval-logloss:0.379887
[1062]	train-logloss:0.357039	eval-logloss:0.379882
[1063]	train-logloss:0.357012	eval-logloss:0.379875
[1064]	train-logloss:0.35699	eval-logloss:0.379871
[1065]	train-logloss:0.356971	eval-logloss:0.379869
[1066]	train-logloss:0.356947	eval-logloss:0.379869
[1067]	train-logloss:0.356912	eval-logloss:0.379857
[1068]	train-logloss:0.356887	eval-logloss:0.379848
[1069]	train-logloss:0.356859	eval-logloss:0.379841
[1070]	train-logloss:0.356832	eval-logloss:0.379837
[1071]	train-logloss:0.356811	eval-logloss:0.379837
[1072]	train-logloss:0.35678	eval-logloss:0.379832
[1073]	train-logloss:0.356758	eval-logloss:0.379829
[1074]	train-logloss:0.356737	eval-logloss:0.379823
[1075]	train-logloss:0.356707	eval-logloss:0.379814
[1076]	train-logloss:0.356682	eval-logloss:0.379807
[1077]	train-logloss:0.356664	eval-logloss:0.379803
[1078]	train-logloss:0.356644	eval-logloss:0.379799
[1079]	train-logloss:0.356621	eval-logloss:0.379795
[1080]	train-logloss:0.3566	eval-logloss:0.379791
[1081]	train-logloss:0.356573	eval-logloss:0.379791
[1082]	train-logloss:0.356539	eval-logloss:0.379781
[1083]	train-logloss:0.356516	eval-logloss:0.379776
[1084]	train-logloss:0.356503	eval-logloss:0.379774
[1085]	train-logloss:0.35649	eval-logloss:0.379774
[1086]	train-logloss:0.356469	eval-logloss:0.379769
[1087]	train-logloss:0.356442	eval-logloss:0.379765
[1088]	train-logloss:0.356422	eval-logloss:0.379767
[1089]	train-logloss:0.356389	eval-logloss:0.379763
[1090]	train-logloss:0.356369	eval-logloss:0.379758
[1091]	train-logloss:0.356346	eval-logloss:0.379757
[1092]	train-logloss:0.356321	eval-logloss:0.379751
[1093]	train-logloss:0.356291	eval-logloss:0.37974
[1094]	train-logloss:0.356274	eval-logloss:0.379735
[1095]	train-logloss:0.356256	eval-logloss:0.379731
[1096]	train-logloss:0.356228	eval-logloss:0.379726
[1097]	train-logloss:0.356204	eval-logloss:0.379719
[1098]	train-logloss:0.356179	eval-logloss:0.379713
[1099]	train-logloss:0.356149	eval-logloss:0.379709
[1100]	train-logloss:0.356129	eval-logloss:0.379707
[1101]	train-logloss:0.356106	eval-logloss:0.379699
[1102]	train-logloss:0.356072	eval-logloss:0.379693
[1103]	train-logloss:0.356049	eval-logloss:0.379693
[1104]	train-logloss:0.356023	eval-logloss:0.379684
[1105]	train-logloss:0.356006	eval-logloss:0.379678
[1106]	train-logloss:0.355991	eval-logloss:0.379679
[1107]	train-logloss:0.355967	eval-logloss:0.379678
[1108]	train-logloss:0.355951	eval-logloss:0.379675
[1109]	train-logloss:0.355931	eval-logloss:0.379674
[1110]	train-logloss:0.355907	eval-logloss:0.379669
[1111]	train-logloss:0.35589	eval-logloss:0.379667
[1112]	train-logloss:0.35587	eval-logloss:0.379666
[1113]	train-logloss:0.355848	eval-logloss:0.37966
[1114]	train-logloss:0.355821	eval-logloss:0.379656
[1115]	train-logloss:0.355796	eval-logloss:0.379646
[1116]	train-logloss:0.355771	eval-logloss:0.379645
[1117]	train-logloss:0.355749	eval-logloss:0.379638
[1118]	train-logloss:0.355736	eval-logloss:0.379636
[1119]	train-logloss:0.355712	eval-logloss:0.379634
[1120]	train-logloss:0.355681	eval-logloss:0.379627
[1121]	train-logloss:0.355658	eval-logloss:0.379621
[1122]	train-logloss:0.355636	eval-logloss:0.379618
[1123]	train-logloss:0.355606	eval-logloss:0.379609
[1124]	train-logloss:0.355577	eval-logloss:0.379601
[1125]	train-logloss:0.35555	eval-logloss:0.379596
[1126]	train-logloss:0.355531	eval-logloss:0.379593
[1127]	train-logloss:0.355503	eval-logloss:0.379587
[1128]	train-logloss:0.355484	eval-logloss:0.379587
[1129]	train-logloss:0.355452	eval-logloss:0.379582

[1130]	train-logloss:0.35543	eval-logloss:0.379584
[1131]	train-logloss:0.355406	eval-logloss:0.37958
[1132]	train-logloss:0.355387	eval-logloss:0.379575
[1133]	train-logloss:0.35536	eval-logloss:0.379572
[1134]	train-logloss:0.355343	eval-logloss:0.379572
[1135]	train-logloss:0.355322	eval-logloss:0.379571
[1136]	train-logloss:0.355306	eval-logloss:0.37957
[1137]	train-logloss:0.355281	eval-logloss:0.379566
[1138]	train-logloss:0.355258	eval-logloss:0.379563
[1139]	train-logloss:0.355234	eval-logloss:0.379561
[1140]	train-logloss:0.355211	eval-logloss:0.379556
[1141]	train-logloss:0.35518	eval-logloss:0.379553
[1142]	train-logloss:0.355148	eval-logloss:0.379552
[1143]	train-logloss:0.355124	eval-logloss:0.379547
[1144]	train-logloss:0.355095	eval-logloss:0.379542
[1145]	train-logloss:0.355066	eval-logloss:0.379541
[1146]	train-logloss:0.355037	eval-logloss:0.379535
[1147]	train-logloss:0.35501	eval-logloss:0.379528
[1148]	train-logloss:0.354984	eval-logloss:0.379525
[1149]	train-logloss:0.354955	eval-logloss:0.37952
[1150]	train-logloss:0.354924	eval-logloss:0.379511
[1151]	train-logloss:0.354892	eval-logloss:0.3795
[1152]	train-logloss:0.354876	eval-logloss:0.379499
[1153]	train-logloss:0.354858	eval-logloss:0.379499
[1154]	train-logloss:0.354835	eval-logloss:0.379503
[1155]	train-logloss:0.354812	eval-logloss:0.3795
[1156]	train-logloss:0.354786	eval-logloss:0.379494
[1157]	train-logloss:0.35475	eval-logloss:0.379487
[1158]	train-logloss:0.354724	eval-logloss:0.379483
[1159]	train-logloss:0.354708	eval-logloss:0.379481
[1160]	train-logloss:0.354683	eval-logloss:0.379474
[1161]	train-logloss:0.354668	eval-logloss:0.379471
[1162]	train-logloss:0.354644	eval-logloss:0.379472
[1163]	train-logloss:0.354617	eval-logloss:0.379469
[1164]	train-logloss:0.354592	eval-logloss:0.379465
[1165]	train-logloss:0.354571	eval-logloss:0.379463
[1166]	train-logloss:0.354552	eval-logloss:0.37946
[1167]	train-logloss:0.354535	eval-logloss:0.379462
[1168]	train-logloss:0.35451	eval-logloss:0.379461
[1169]	train-logloss:0.354497	eval-logloss:0.379459
[1170]	train-logloss:0.354477	eval-logloss:0.379454
[1171]	train-logloss:0.354452	eval-logloss:0.379453
[1172]	train-logloss:0.354425	eval-logloss:0.379446
[1173]	train-logloss:0.354392	eval-logloss:0.379439
[1174]	train-logloss:0.354375	eval-logloss:0.379435
[1175]	train-logloss:0.354348	eval-logloss:0.379433
[1176]	train-logloss:0.354327	eval-logloss:0.379435
[1177]	train-logloss:0.35431	eval-logloss:0.379433
[1178]	train-logloss:0.354286	eval-logloss:0.379433
[1179]	train-logloss:0.354262	eval-logloss:0.379431
[1180]	train-logloss:0.354233	eval-logloss:0.379428
[1181]	train-logloss:0.354204	eval-logloss:0.37942
[1182]	train-logloss:0.354176	eval-logloss:0.379412
[1183]	train-logloss:0.354149	eval-logloss:0.379407
[1184]	train-logloss:0.354125	eval-logloss:0.379402
[1185]	train-logloss:0.3541	eval-logloss:0.379398
[1186]	train-logloss:0.354085	eval-logloss:0.379393
[1187]	train-logloss:0.354058	eval-logloss:0.379391
[1188]	train-logloss:0.354028	eval-logloss:0.379389
[1189]	train-logloss:0.354004	eval-logloss:0.379387
[1190]	train-logloss:0.353974	eval-logloss:0.379383
[1191]	train-logloss:0.353949	eval-logloss:0.379378
[1192]	train-logloss:0.353933	eval-logloss:0.379373
[1193]	train-logloss:0.353911	eval-logloss:0.379371
[1194]	train-logloss:0.353889	eval-logloss:0.37937
[1195]	train-logloss:0.353868	eval-logloss:0.379365
[1196]	train-logloss:0.35385	eval-logloss:0.379364
[1197]	train-logloss:0.353829	eval-logloss:0.379363
[1198]	train-logloss:0.353808	eval-logloss:0.379361
[1199]	train-logloss:0.353785	eval-logloss:0.379355
[1200]	train-logloss:0.353755	eval-logloss:0.37935
[1201]	train-logloss:0.353732	eval-logloss:0.379345
[1202]	train-logloss:0.353716	eval-logloss:0.379345
[1203]	train-logloss:0.353688	eval-logloss:0.379344
[1204]	train-logloss:0.353659	eval-logloss:0.379344
[1205]	train-logloss:0.353647	eval-logloss:0.379343
[1206]	train-logloss:0.353625	eval-logloss:0.379341
[1207]	train-logloss:0.353605	eval-logloss:0.379338
[1208]	train-logloss:0.353576	eval-logloss:0.379333
[1209]	train-logloss:0.353551	eval-logloss:0.37933
[1210]	train-logloss:0.353528	eval-logloss:0.379324
[1211]	train-logloss:0.3535	eval-logloss:0.379322
[1212]	train-logloss:0.353474	eval-logloss:0.379317
[1213]	train-logloss:0.353452	eval-logloss:0.379314
[1214]	train-logloss:0.353423	eval-logloss:0.379307
[1215]	train-logloss:0.353402	eval-logloss:0.379304
[1216]	train-logloss:0.353379	eval-logloss:0.3793
[1217]	train-logloss:0.35336	eval-logloss:0.379298
[1218]	train-logloss:0.353337	eval-logloss:0.379294
[1219]	train-logloss:0.35331	eval-logloss:0.379289
[1220]	train-logloss:0.353291	eval-logloss:0.379291
[1221]	train-logloss:0.353268	eval-logloss:0.379289
[1222]	train-logloss:0.353253	eval-logloss:0.379285
[1223]	train-logloss:0.353236	eval-logloss:0.379281
[1224]	train-logloss:0.353219	eval-logloss:0.379276
[1225]	train-logloss:0.353194	eval-logloss:0.379272
[1226]	train-logloss:0.353167	eval-logloss:0.379272
[1227]	train-logloss:0.353143	eval-logloss:0.379268
[1228]	train-logloss:0.35313	eval-logloss:0.379263
[1229]	train-logloss:0.3531	eval-logloss:0.379257
[1230]	train-logloss:0.353073	eval-logloss:0.379251
[1231]	train-logloss:0.353058	eval-logloss:0.379248
[1232]	train-logloss:0.353029	eval-logloss:0.379247
[1233]	train-logloss:0.353016	eval-logloss:0.379245
[1234]	train-logloss:0.352989	eval-logloss:0.379234
[1235]	train-logloss:0.352972	eval-logloss:0.379232
[1236]	train-logloss:0.352943	eval-logloss:0.379227
[1237]	train-logloss:0.352914	eval-logloss:0.379223
[1238]	train-logloss:0.352893	eval-logloss:0.379219
[1239]	train-logloss:0.352871	eval-logloss:0.379213
[1240]	train-logloss:0.35285	eval-logloss:0.37921
[1241]	train-logloss:0.352822	eval-logloss:0.379207
[1242]	train-logloss:0.352805	eval-logloss:0.379203
[1243]	train-logloss:0.35278	eval-logloss:0.379201
[1244]	train-logloss:0.352754	eval-logloss:0.379196
[1245]	train-logloss:0.35274	eval-logloss:0.379194
[1246]	train-logloss:0.352723	eval-logloss:0.379193
[1247]	train-logloss:0.352693	eval-logloss:0.379184
[1248]	train-logloss:0.35267	eval-logloss:0.379181
[1249]	train-logloss:0.352649	eval-logloss:0.379176
[1250]	train-logloss:0.352625	eval-logloss:0.379175
[1251]	train-logloss:0.352602	eval-logloss:0.379169
[1252]	train-logloss:0.352576	eval-logloss:0.379163
[1253]	train-logloss:0.352555	eval-logloss:0.379162
[1254]	train-logloss:0.352524	eval-logloss:0.37916
[1255]	train-logloss:0.352497	eval-logloss:0.379154
[1256]	train-logloss:0.352483	eval-logloss:0.379156
[1257]	train-logloss:0.352463	eval-logloss:0.379151
[1258]	train-logloss:0.352445	eval-logloss:0.379148
[1259]	train-logloss:0.352419	eval-logloss:0.37914
[1260]	train-logloss:0.352394	eval-logloss:0.379137
[1261]	train-logloss:0.352369	eval-logloss:0.379132
[1262]	train-logloss:0.352351	eval-logloss:0.379127
[1263]	train-logloss:0.352326	eval-logloss:0.379123
[1264]	train-logloss:0.352311	eval-logloss:0.379123
[1265]	train-logloss:0.352288	eval-logloss:0.379121
[1266]	train-logloss:0.352261	eval-logloss:0.379118
[1267]	train-logloss:0.35224	eval-logloss:0.379114
[1268]	train-logloss:0.352221	eval-logloss:0.37911
[1269]	train-logloss:0.352199	eval-logloss:0.379105
[1270]	train-logloss:0.352176	eval-logloss:0.379103
[1271]	train-logloss:0.352156	eval-logloss:0.3791
[1272]	train-logloss:0.35213	eval-logloss:0.379099
[1273]	train-logloss:0.35211	eval-logloss:0.379097
[1274]	train-logloss:0.35209	eval-logloss:0.379092
[1275]	train-logloss:0.35207	eval-logloss:0.37909
[1276]	train-logloss:0.352048	eval-logloss:0.379087
[1277]	train-logloss:0.352018	eval-logloss:0.379083
[1278]	train-logloss:0.351989	eval-logloss:0.379082
[1279]	train-logloss:0.351971	eval-logloss:0.37908
[1280]	train-logloss:0.351948	eval-logloss:0.379077
[1281]	train-logloss:0.351923	eval-logloss:0.379072
[1282]	train-logloss:0.351905	eval-logloss:0.379073
[1283]	train-logloss:0.351884	eval-logloss:0.379073
[1284]	train-logloss:0.351864	eval-logloss:0.37907
[1285]	train-logloss:0.351843	eval-logloss:0.379066
[1286]	train-logloss:0.351817	eval-logloss:0.379063
[1287]	train-logloss:0.351792	eval-logloss:0.379063
[1288]	train-logloss:0.351767	eval-logloss:0.37906

[1289]	train-logloss:0.351746	eval-logloss:0.379055
[1290]	train-logloss:0.351725	eval-logloss:0.37905
[1291]	train-logloss:0.351701	eval-logloss:0.379046
[1292]	train-logloss:0.351672	eval-logloss:0.379038
[1293]	train-logloss:0.351647	eval-logloss:0.379033
[1294]	train-logloss:0.351619	eval-logloss:0.379027
[1295]	train-logloss:0.351595	eval-logloss:0.379023
[1296]	train-logloss:0.351579	eval-logloss:0.379018
[1297]	train-logloss:0.351557	eval-logloss:0.379019
[1298]	train-logloss:0.351534	eval-logloss:0.379017
[1299]	train-logloss:0.351508	eval-logloss:0.37901
[1300]	train-logloss:0.351491	eval-logloss:0.379006
[1301]	train-logloss:0.351467	eval-logloss:0.379005
[1302]	train-logloss:0.351444	eval-logloss:0.379005
[1303]	train-logloss:0.351419	eval-logloss:0.379
[1304]	train-logloss:0.3514	eval-logloss:0.379
[1305]	train-logloss:0.351384	eval-logloss:0.378998
[1306]	train-logloss:0.351363	eval-logloss:0.378997
[1307]	train-logloss:0.351342	eval-logloss:0.378994
[1308]	train-logloss:0.351322	eval-logloss:0.378993
[1309]	train-logloss:0.351297	eval-logloss:0.378988
[1310]	train-logloss:0.351279	eval-logloss:0.378989
[1311]	train-logloss:0.351256	eval-logloss:0.378983
[1312]	train-logloss:0.351235	eval-logloss:0.378979
[1313]	train-logloss:0.351213	eval-logloss:0.37898
[1314]	train-logloss:0.351201	eval-logloss:0.378978
[1315]	train-logloss:0.351179	eval-logloss:0.378973
[1316]	train-logloss:0.351154	eval-logloss:0.37897
[1317]	train-logloss:0.351136	eval-logloss:0.378966
[1318]	train-logloss:0.351112	eval-logloss:0.378966
[1319]	train-logloss:0.351095	eval-logloss:0.378964
[1320]	train-logloss:0.351074	eval-logloss:0.378965
[1321]	train-logloss:0.351057	eval-logloss:0.37896
[1322]	train-logloss:0.351032	eval-logloss:0.378957
[1323]	train-logloss:0.351012	eval-logloss:0.378954
[1324]	train-logloss:0.350995	eval-logloss:0.378948
[1325]	train-logloss:0.350976	eval-logloss:0.378945
[1326]	train-logloss:0.350956	eval-logloss:0.378945
[1327]	train-logloss:0.350928	eval-logloss:0.378941
[1328]	train-logloss:0.350901	eval-logloss:0.378936
[1329]	train-logloss:0.350879	eval-logloss:0.378936
[1330]	train-logloss:0.350855	eval-logloss:0.378932
[1331]	train-logloss:0.350844	eval-logloss:0.378932
[1332]	train-logloss:0.35082	eval-logloss:0.378924
[1333]	train-logloss:0.350793	eval-logloss:0.378916
[1334]	train-logloss:0.350767	eval-logloss:0.378914
[1335]	train-logloss:0.350744	eval-logloss:0.378912
[1336]	train-logloss:0.350727	eval-logloss:0.378909
[1337]	train-logloss:0.350701	eval-logloss:0.378906
[1338]	train-logloss:0.350673	eval-logloss:0.378903
[1339]	train-logloss:0.350647	eval-logloss:0.378902
[1340]	train-logloss:0.350627	eval-logloss:0.378901
[1341]	train-logloss:0.350605	eval-logloss:0.378902
[1342]	train-logloss:0.350583	eval-logloss:0.378897
[1343]	train-logloss:0.350562	eval-logloss:0.378892
[1344]	train-logloss:0.350534	eval-logloss:0.378888
[1345]	train-logloss:0.350508	eval-logloss:0.378884
[1346]	train-logloss:0.350489	eval-logloss:0.378878
[1347]	train-logloss:0.350461	eval-logloss:0.378879
[1348]	train-logloss:0.350437	eval-logloss:0.378875
[1349]	train-logloss:0.35042	eval-logloss:0.378878
[1350]	train-logloss:0.350403	eval-logloss:0.378876
[1351]	train-logloss:0.350383	eval-logloss:0.378873
[1352]	train-logloss:0.350373	eval-logloss:0.378875
[1353]	train-logloss:0.350356	eval-logloss:0.378873
[1354]	train-logloss:0.350341	eval-logloss:0.378873
[1355]	train-logloss:0.350321	eval-logloss:0.378869
[1356]	train-logloss:0.350291	eval-logloss:0.378865
[1357]	train-logloss:0.350265	eval-logloss:0.378861
[1358]	train-logloss:0.350245	eval-logloss:0.378854
[1359]	train-logloss:0.350228	eval-logloss:0.37885
[1360]	train-logloss:0.350208	eval-logloss:0.378848
[1361]	train-logloss:0.35019	eval-logloss:0.378846
[1362]	train-logloss:0.35017	eval-logloss:0.378844
[1363]	train-logloss:0.350145	eval-logloss:0.37884
[1364]	train-logloss:0.350124	eval-logloss:0.378837
[1365]	train-logloss:0.350098	eval-logloss:0.378832
[1366]	train-logloss:0.350077	eval-logloss:0.378832
[1367]	train-logloss:0.350062	eval-logloss:0.378831
[1368]	train-logloss:0.350035	eval-logloss:0.37883
[1369]	train-logloss:0.350013	eval-logloss:0.378824
[1370]	train-logloss:0.34999	eval-logloss:0.378821
[1371]	train-logloss:0.349976	eval-logloss:0.37882
[1372]	train-logloss:0.349968	eval-logloss:0.37882
[1373]	train-logloss:0.349953	eval-logloss:0.378816
[1374]	train-logloss:0.349939	eval-logloss:0.378814
[1375]	train-logloss:0.349919	eval-logloss:0.37881
[1376]	train-logloss:0.349905	eval-logloss:0.37881
[1377]	train-logloss:0.349883	eval-logloss:0.378809
[1378]	train-logloss:0.349861	eval-logloss:0.378803
[1379]	train-logloss:0.349841	eval-logloss:0.378802
[1380]	train-logloss:0.349821	eval-logloss:0.378802
[1381]	train-logloss:0.349808	eval-logloss:0.378801
[1382]	train-logloss:0.349784	eval-logloss:0.3788
[1383]	train-logloss:0.349759	eval-logloss:0.3788
[1384]	train-logloss:0.349745	eval-logloss:0.378798
[1385]	train-logloss:0.349725	eval-logloss:0.378797
[1386]	train-logloss:0.349704	eval-logloss:0.378797
[1387]	train-logloss:0.349685	eval-logloss:0.378796
[1388]	train-logloss:0.349667	eval-logloss:0.378793
[1389]	train-logloss:0.34965	eval-logloss:0.378791
[1390]	train-logloss:0.349633	eval-logloss:0.378789
[1391]	train-logloss:0.349609	eval-logloss:0.378787
[1392]	train-logloss:0.349581	eval-logloss:0.378784
[1393]	train-logloss:0.34956	eval-logloss:0.37878
[1394]	train-logloss:0.349534	eval-logloss:0.37878
[1395]	train-logloss:0.349508	eval-logloss:0.378777
[1396]	train-logloss:0.349478	eval-logloss:0.378774
[1397]	train-logloss:0.349453	eval-logloss:0.37877
[1398]	train-logloss:0.34944	eval-logloss:0.378771
[1399]	train-logloss:0.349417	eval-logloss:0.378766
[1400]	train-logloss:0.349397	eval-logloss:0.378766
[1401]	train-logloss:0.349373	eval-logloss:0.378762
[1402]	train-logloss:0.349342	eval-logloss:0.378756
[1403]	train-logloss:0.349326	eval-logloss:0.378753
[1404]	train-logloss:0.349303	eval-logloss:0.378752
[1405]	train-logloss:0.349287	eval-logloss:0.378748
[1406]	train-logloss:0.349268	eval-logloss:0.378745
[1407]	train-logloss:0.349243	eval-logloss:0.37874
[1408]	train-logloss:0.349223	eval-logloss:0.378739
[1409]	train-logloss:0.349202	eval-logloss:0.378742
[1410]	train-logloss:0.349186	eval-logloss:0.378742
[1411]	train-logloss:0.349168	eval-logloss:0.378737
[1412]	train-logloss:0.349154	eval-logloss:0.378735
[1413]	train-logloss:0.349133	eval-logloss:0.378732
[1414]	train-logloss:0.349113	eval-logloss:0.378727
[1415]	train-logloss:0.349098	eval-logloss:0.378727
[1416]	train-logloss:0.349075	eval-logloss:0.378725
[1417]	train-logloss:0.349052	eval-logloss:0.378724
[1418]	train-logloss:0.349031	eval-logloss:0.378721
[1419]	train-logloss:0.349007	eval-logloss:0.37872
[1420]	train-logloss:0.348987	eval-logloss:0.378714
[1421]	train-logloss:0.348968	eval-logloss:0.378715
[1422]	train-logloss:0.348943	eval-logloss:0.378713
[1423]	train-logloss:0.348927	eval-logloss:0.378711
[1424]	train-logloss:0.34892	eval-logloss:0.378711
[1425]	train-logloss:0.348906	eval-logloss:0.378711
[1426]	train-logloss:0.348886	eval-logloss:0.378709
[1427]	train-logloss:0.348867	eval-logloss:0.378709
[1428]	train-logloss:0.348852	eval-logloss:0.378704
[1429]	train-logloss:0.348829	eval-logloss:0.378702
[1430]	train-logloss:0.348816	eval-logloss:0.378701
[1431]	train-logloss:0.348801	eval-logloss:0.378697
[1432]	train-logloss:0.348773	eval-logloss:0.378698
[1433]	train-logloss:0.348762	eval-logloss:0.378697
[1434]	train-logloss:0.348743	eval-logloss:0.378694
[1435]	train-logloss:0.348728	eval-logloss:0.378695
[1436]	train-logloss:0.348701	eval-logloss:0.378692
[1437]	train-logloss:0.348689	eval-logloss:0.378689
[1438]	train-logloss:0.348672	eval-logloss:0.378684
[1439]	train-logloss:0.348654	eval-logloss:0.378686
[1440]	train-logloss:0.348634	eval-logloss:0.378684
[1441]	train-logloss:0.348618	eval-logloss:0.378682
[1442]	train-logloss:0.348603	eval-logloss:0.378682
[1443]	train-logloss:0.348571	eval-logloss:0.378683
[1444]	train-logloss:0.348546	eval-logloss:0.37868
[1445]	train-logloss:0.348519	eval-logloss:0.37868
[1446]	train-logloss:0.348496	eval-logloss:0.378683
[1447]	train-logloss:0.348466	eval-logloss:0.378679

[1448]	train-logloss:0.348444	eval-logloss:0.378682
[1449]	train-logloss:0.348421	eval-logloss:0.378678
[1450]	train-logloss:0.348403	eval-logloss:0.378675
[1451]	train-logloss:0.348377	eval-logloss:0.378676
[1452]	train-logloss:0.348362	eval-logloss:0.378673
[1453]	train-logloss:0.34835	eval-logloss:0.378674
[1454]	train-logloss:0.348321	eval-logloss:0.378667
[1455]	train-logloss:0.34831	eval-logloss:0.378663
[1456]	train-logloss:0.348298	eval-logloss:0.37866
[1457]	train-logloss:0.348283	eval-logloss:0.378659
[1458]	train-logloss:0.348258	eval-logloss:0.378654
[1459]	train-logloss:0.34824	eval-logloss:0.378651
[1460]	train-logloss:0.348216	eval-logloss:0.378651
[1461]	train-logloss:0.348188	eval-logloss:0.378654
[1462]	train-logloss:0.348162	eval-logloss:0.378653
[1463]	train-logloss:0.348149	eval-logloss:0.378652
[1464]	train-logloss:0.348124	eval-logloss:0.378649
[1465]	train-logloss:0.348108	eval-logloss:0.37865
[1466]	train-logloss:0.348091	eval-logloss:0.378647
[1467]	train-logloss:0.34807	eval-logloss:0.378642
[1468]	train-logloss:0.348047	eval-logloss:0.378635
[1469]	train-logloss:0.348036	eval-logloss:0.378633
[1470]	train-logloss:0.348012	eval-logloss:0.378633
[1471]	train-logloss:0.347992	eval-logloss:0.378632
[1472]	train-logloss:0.347969	eval-logloss:0.378629
[1473]	train-logloss:0.347951	eval-logloss:0.378627
[1474]	train-logloss:0.347927	eval-logloss:0.378626
[1475]	train-logloss:0.347911	eval-logloss:0.378627
[1476]	train-logloss:0.347897	eval-logloss:0.378629
[1477]	train-logloss:0.347873	eval-logloss:0.378629
[1478]	train-logloss:0.34785	eval-logloss:0.378625
[1479]	train-logloss:0.34783	eval-logloss:0.378622
[1480]	train-logloss:0.347815	eval-logloss:0.378621
[1481]	train-logloss:0.347796	eval-logloss:0.378618
[1482]	train-logloss:0.347776	eval-logloss:0.378614
[1483]	train-logloss:0.347759	eval-logloss:0.378616
[1484]	train-logloss:0.347735	eval-logloss:0.378617
[1485]	train-logloss:0.347719	eval-logloss:0.378614
[1486]	train-logloss:0.347689	eval-logloss:0.37861
[1487]	train-logloss:0.347674	eval-logloss:0.378611
[1488]	train-logloss:0.347657	eval-logloss:0.378609
[1489]	train-logloss:0.347643	eval-logloss:0.378613
[1490]	train-logloss:0.347626	eval-logloss:0.378612
[1491]	train-logloss:0.347605	eval-logloss:0.378613
[1492]	train-logloss:0.347583	eval-logloss:0.378612
[1493]	train-logloss:0.347573	eval-logloss:0.378613
[1494]	train-logloss:0.347553	eval-logloss:0.378612
[1495]	train-logloss:0.347525	eval-logloss:0.378607
[1496]	train-logloss:0.347515	eval-logloss:0.378607
[1497]	train-logloss:0.347507	eval-logloss:0.378606
[1498]	train-logloss:0.347489	eval-logloss:0.378604
[1499]	train-logloss:0.347478	eval-logloss:0.378603
[1500]	train-logloss:0.347458	eval-logloss:0.378599
[1501]	train-logloss:0.347439	eval-logloss:0.378597
[1502]	train-logloss:0.347412	eval-logloss:0.378595
[1503]	train-logloss:0.347393	eval-logloss:0.378588
[1504]	train-logloss:0.347376	eval-logloss:0.378587
[1505]	train-logloss:0.347357	eval-logloss:0.378587
[1506]	train-logloss:0.34734	eval-logloss:0.378589
[1507]	train-logloss:0.347326	eval-logloss:0.378588
[1508]	train-logloss:0.347307	eval-logloss:0.378589
[1509]	train-logloss:0.347285	eval-logloss:0.378584
[1510]	train-logloss:0.347267	eval-logloss:0.378585
[1511]	train-logloss:0.347248	eval-logloss:0.378584
[1512]	train-logloss:0.347226	eval-logloss:0.378584
[1513]	train-logloss:0.347201	eval-logloss:0.378579
[1514]	train-logloss:0.347186	eval-logloss:0.378579
[1515]	train-logloss:0.347168	eval-logloss:0.378577
[1516]	train-logloss:0.347154	eval-logloss:0.378577
[1517]	train-logloss:0.347133	eval-logloss:0.378574
[1518]	train-logloss:0.347116	eval-logloss:0.378571
[1519]	train-logloss:0.347091	eval-logloss:0.378567
[1520]	train-logloss:0.347069	eval-logloss:0.378566
[1521]	train-logloss:0.347052	eval-logloss:0.378566
[1522]	train-logloss:0.347033	eval-logloss:0.378566
[1523]	train-logloss:0.347006	eval-logloss:0.378562
[1524]	train-logloss:0.346985	eval-logloss:0.378567
[1525]	train-logloss:0.346965	eval-logloss:0.378565
[1526]	train-logloss:0.346947	eval-logloss:0.378567
[1527]	train-logloss:0.346924	eval-logloss:0.378564
[1528]	train-logloss:0.346911	eval-logloss:0.378564
[1529]	train-logloss:0.346893	eval-logloss:0.378563
[1530]	train-logloss:0.346878	eval-logloss:0.378561
[1531]	train-logloss:0.346853	eval-logloss:0.378552
[1532]	train-logloss:0.346841	eval-logloss:0.378552
[1533]	train-logloss:0.34682	eval-logloss:0.378547
[1534]	train-logloss:0.346797	eval-logloss:0.378545
[1535]	train-logloss:0.346784	eval-logloss:0.378543
[1536]	train-logloss:0.346765	eval-logloss:0.378545
[1537]	train-logloss:0.34675	eval-logloss:0.378541
[1538]	train-logloss:0.34673	eval-logloss:0.378539
[1539]	train-logloss:0.346717	eval-logloss:0.378541
[1540]	train-logloss:0.346697	eval-logloss:0.378542
[1541]	train-logloss:0.346672	eval-logloss:0.378541
[1542]	train-logloss:0.34665	eval-logloss:0.378538
[1543]	train-logloss:0.34664	eval-logloss:0.378537
[1544]	train-logloss:0.346616	eval-logloss:0.378539
[1545]	train-logloss:0.346595	eval-logloss:0.378537
[1546]	train-logloss:0.346577	eval-logloss:0.378537
[1547]	train-logloss:0.346561	eval-logloss:0.378538
[1548]	train-logloss:0.346534	eval-logloss:0.378535
[1549]	train-logloss:0.346524	eval-logloss:0.378535
[1550]	train-logloss:0.346509	eval-logloss:0.378534
[1551]	train-logloss:0.346492	eval-logloss:0.378532
[1552]	train-logloss:0.346471	eval-logloss:0.378527
[1553]	train-logloss:0.346459	eval-logloss:0.378526
[1554]	train-logloss:0.346441	eval-logloss:0.378526
[1555]	train-logloss:0.346419	eval-logloss:0.378523
[1556]	train-logloss:0.346398	eval-logloss:0.378519
[1557]	train-logloss:0.346378	eval-logloss:0.378518
[1558]	train-logloss:0.34636	eval-logloss:0.378514
[1559]	train-logloss:0.346339	eval-logloss:0.378515
[1560]	train-logloss:0.346329	eval-logloss:0.378515
[1561]	train-logloss:0.346311	eval-logloss:0.378515
[1562]	train-logloss:0.346286	eval-logloss:0.378515
[1563]	train-logloss:0.346264	eval-logloss:0.378514
[1564]	train-logloss:0.346248	eval-logloss:0.378514
[1565]	train-logloss:0.346222	eval-logloss:0.378511
[1566]	train-logloss:0.3462	eval-logloss:0.378511
[1567]	train-logloss:0.346188	eval-logloss:0.378509
[1568]	train-logloss:0.34616	eval-logloss:0.378512
[1569]	train-logloss:0.346149	eval-logloss:0.37851
[1570]	train-logloss:0.346131	eval-logloss:0.378509
[1571]	train-logloss:0.346114	eval-logloss:0.378505
[1572]	train-logloss:0.346084	eval-logloss:0.378501
[1573]	train-logloss:0.346071	eval-logloss:0.3785
[1574]	train-logloss:0.346058	eval-logloss:0.378501
[1575]	train-logloss:0.346038	eval-logloss:0.3785
[1576]	train-logloss:0.346023	eval-logloss:0.378502
[1577]	train-logloss:0.346006	eval-logloss:0.378503
[1578]	train-logloss:0.345985	eval-logloss:0.378503
[1579]	train-logloss:0.345962	eval-logloss:0.378503
[1580]	train-logloss:0.345944	eval-logloss:0.3785
[1581]	train-logloss:0.345937	eval-logloss:0.378498
[1582]	train-logloss:0.345918	eval-logloss:0.378498
[1583]	train-logloss:0.345897	eval-logloss:0.378494
[1584]	train-logloss:0.345874	eval-logloss:0.378494
[1585]	train-logloss:0.345854	eval-logloss:0.378496
[1586]	train-logloss:0.345837	eval-logloss:0.378497
[1587]	train-logloss:0.345814	eval-logloss:0.378496
[1588]	train-logloss:0.345787	eval-logloss:0.378492
[1589]	train-logloss:0.345768	eval-logloss:0.378492
[1590]	train-logloss:0.345745	eval-logloss:0.378491
[1591]	train-logloss:0.345729	eval-logloss:0.378487
[1592]	train-logloss:0.345707	eval-logloss:0.378482
[1593]	train-logloss:0.345697	eval-logloss:0.378481
[1594]	train-logloss:0.345682	eval-logloss:0.378477
[1595]	train-logloss:0.345662	eval-logloss:0.378477
[1596]	train-logloss:0.345648	eval-logloss:0.378478
[1597]	train-logloss:0.345632	eval-logloss:0.378477
[1598]	train-logloss:0.345611	eval-logloss:0.378476
[1599]	train-logloss:0.345591	eval-logloss:0.378475
[1600]	train-logloss:0.345577	eval-logloss:0.378472
[1601]	train-logloss:0.345558	eval-logloss:0.37847
[1602]	train-logloss:0.345537	eval-logloss:0.378467
[1603]	train-logloss:0.345518	eval-logloss:0.378465
[1604]	train-logloss:0.345498	eval-logloss:0.378464
[1605]	train-logloss:0.345482	eval-logloss:0.378462
[1606]	train-logloss:0.345466	eval-logloss:0.378462

[1607]	train-logloss:0.345448	eval-logloss:0.378459
[1608]	train-logloss:0.345427	eval-logloss:0.378458
[1609]	train-logloss:0.345411	eval-logloss:0.378456
[1610]	train-logloss:0.345396	eval-logloss:0.378457
[1611]	train-logloss:0.345378	eval-logloss:0.378458
[1612]	train-logloss:0.345358	eval-logloss:0.378455
[1613]	train-logloss:0.345342	eval-logloss:0.378457
[1614]	train-logloss:0.345323	eval-logloss:0.378458
[1615]	train-logloss:0.345306	eval-logloss:0.378457
[1616]	train-logloss:0.345288	eval-logloss:0.378459
[1617]	train-logloss:0.345268	eval-logloss:0.378452
[1618]	train-logloss:0.345244	eval-logloss:0.378449
[1619]	train-logloss:0.34523	eval-logloss:0.37845
[1620]	train-logloss:0.345209	eval-logloss:0.378448
[1621]	train-logloss:0.345189	eval-logloss:0.378448
[1622]	train-logloss:0.34518	eval-logloss:0.378448
[1623]	train-logloss:0.345169	eval-logloss:0.378445
[1624]	train-logloss:0.345155	eval-logloss:0.378445
[1625]	train-logloss:0.345129	eval-logloss:0.378442
[1626]	train-logloss:0.345108	eval-logloss:0.37844
[1627]	train-logloss:0.34508	eval-logloss:0.378436
[1628]	train-logloss:0.345062	eval-logloss:0.378435
[1629]	train-logloss:0.345045	eval-logloss:0.378436
[1630]	train-logloss:0.345034	eval-logloss:0.378433
[1631]	train-logloss:0.345013	eval-logloss:0.378429
[1632]	train-logloss:0.344996	eval-logloss:0.378427
[1633]	train-logloss:0.344976	eval-logloss:0.378425
[1634]	train-logloss:0.344951	eval-logloss:0.378422
[1635]	train-logloss:0.344934	eval-logloss:0.378422
[1636]	train-logloss:0.344909	eval-logloss:0.37842
[1637]	train-logloss:0.344895	eval-logloss:0.378417
[1638]	train-logloss:0.344879	eval-logloss:0.378416
[1639]	train-logloss:0.344857	eval-logloss:0.378413
[1640]	train-logloss:0.344849	eval-logloss:0.378413
[1641]	train-logloss:0.344835	eval-logloss:0.378416
[1642]	train-logloss:0.344818	eval-logloss:0.378413
[1643]	train-logloss:0.344795	eval-logloss:0.378413
[1644]	train-logloss:0.344772	eval-logloss:0.378409
[1645]	train-logloss:0.344753	eval-logloss:0.378407
[1646]	train-logloss:0.34473	eval-logloss:0.378404
[1647]	train-logloss:0.34471	eval-logloss:0.378403
[1648]	train-logloss:0.344695	eval-logloss:0.378401
[1649]	train-logloss:0.344677	eval-logloss:0.378402
[1650]	train-logloss:0.344656	eval-logloss:0.378399
[1651]	train-logloss:0.344636	eval-logloss:0.378394
[1652]	train-logloss:0.34462	eval-logloss:0.378394
[1653]	train-logloss:0.344599	eval-logloss:0.378391
[1654]	train-logloss:0.344581	eval-logloss:0.37839
[1655]	train-logloss:0.344568	eval-logloss:0.37839
[1656]	train-logloss:0.344557	eval-logloss:0.378387
[1657]	train-logloss:0.344548	eval-logloss:0.378386
[1658]	train-logloss:0.344526	eval-logloss:0.378388
[1659]	train-logloss:0.344509	eval-logloss:0.378387
[1660]	train-logloss:0.344495	eval-logloss:0.378387
[1661]	train-logloss:0.344478	eval-logloss:0.378388
[1662]	train-logloss:0.344461	eval-logloss:0.378388
[1663]	train-logloss:0.344448	eval-logloss:0.37839
[1664]	train-logloss:0.344441	eval-logloss:0.378389
[1665]	train-logloss:0.344429	eval-logloss:0.378389
[1666]	train-logloss:0.344422	eval-logloss:0.378389
[1667]	train-logloss:0.344409	eval-logloss:0.378388
[1668]	train-logloss:0.344394	eval-logloss:0.378387
[1669]	train-logloss:0.344374	eval-logloss:0.378384
[1670]	train-logloss:0.344367	eval-logloss:0.378385
[1671]	train-logloss:0.344348	eval-logloss:0.378383
[1672]	train-logloss:0.344328	eval-logloss:0.378387
[1673]	train-logloss:0.344312	eval-logloss:0.378384
[1674]	train-logloss:0.344301	eval-logloss:0.378385
[1675]	train-logloss:0.344286	eval-logloss:0.378383
[1676]	train-logloss:0.344267	eval-logloss:0.378381
[1677]	train-logloss:0.344252	eval-logloss:0.378383
[1678]	train-logloss:0.344245	eval-logloss:0.37838
[1679]	train-logloss:0.344234	eval-logloss:0.378382
[1680]	train-logloss:0.344222	eval-logloss:0.378382
[1681]	train-logloss:0.344206	eval-logloss:0.378381
[1682]	train-logloss:0.344195	eval-logloss:0.378382
[1683]	train-logloss:0.344173	eval-logloss:0.378378
[1684]	train-logloss:0.344158	eval-logloss:0.378377
[1685]	train-logloss:0.344143	eval-logloss:0.378377
[1686]	train-logloss:0.344135	eval-logloss:0.378378
[1687]	train-logloss:0.344118	eval-logloss:0.378378
[1688]	train-logloss:0.344103	eval-logloss:0.378377
[1689]	train-logloss:0.344084	eval-logloss:0.378376
[1690]	train-logloss:0.344072	eval-logloss:0.378373
[1691]	train-logloss:0.34406	eval-logloss:0.378372
[1692]	train-logloss:0.344043	eval-logloss:0.378372
[1693]	train-logloss:0.344033	eval-logloss:0.378368
[1694]	train-logloss:0.344018	eval-logloss:0.378365
[1695]	train-logloss:0.343998	eval-logloss:0.37836
[1696]	train-logloss:0.343976	eval-logloss:0.378357
[1697]	train-logloss:0.343963	eval-logloss:0.378357
[1698]	train-logloss:0.343949	eval-logloss:0.378354
[1699]	train-logloss:0.343927	eval-logloss:0.378353
[1700]	train-logloss:0.343911	eval-logloss:0.378351
[1701]	train-logloss:0.343896	eval-logloss:0.378348
[1702]	train-logloss:0.34389	eval-logloss:0.378348
[1703]	train-logloss:0.343874	eval-logloss:0.378347
[1704]	train-logloss:0.343851	eval-logloss:0.378346
[1705]	train-logloss:0.343839	eval-logloss:0.378346
[1706]	train-logloss:0.343815	eval-logloss:0.378347
[1707]	train-logloss:0.343798	eval-logloss:0.378344
[1708]	train-logloss:0.343785	eval-logloss:0.378341
[1709]	train-logloss:0.343774	eval-logloss:0.378338
[1710]	train-logloss:0.343751	eval-logloss:0.378338
[1711]	train-logloss:0.34374	eval-logloss:0.378337
[1712]	train-logloss:0.343726	eval-logloss:0.378337
[1713]	train-logloss:0.343707	eval-logloss:0.378334
[1714]	train-logloss:0.343683	eval-logloss:0.37833
[1715]	train-logloss:0.343668	eval-logloss:0.378329
[1716]	train-logloss:0.34365	eval-logloss:0.378326
[1717]	train-logloss:0.343638	eval-logloss:0.378324
[1718]	train-logloss:0.343619	eval-logloss:0.378321
[1719]	train-logloss:0.343602	eval-logloss:0.378321
[1720]	train-logloss:0.343582	eval-logloss:0.378323
[1721]	train-logloss:0.343566	eval-logloss:0.378322
[1722]	train-logloss:0.343548	eval-logloss:0.378321
[1723]	train-logloss:0.343533	eval-logloss:0.378321
[1724]	train-logloss:0.343519	eval-logloss:0.378319
[1725]	train-logloss:0.343502	eval-logloss:0.37832
[1726]	train-logloss:0.343479	eval-logloss:0.378322
[1727]	train-logloss:0.343461	eval-logloss:0.378321
[1728]	train-logloss:0.343447	eval-logloss:0.378321
[1729]	train-logloss:0.343437	eval-logloss:0.378321
[1730]	train-logloss:0.343428	eval-logloss:0.378322
[1731]	train-logloss:0.343406	eval-logloss:0.378322
[1732]	train-logloss:0.343397	eval-logloss:0.378323
[1733]	train-logloss:0.343384	eval-logloss:0.37832
[1734]	train-logloss:0.343366	eval-logloss:0.378319
[1735]	train-logloss:0.343349	eval-logloss:0.378322
[1736]	train-logloss:0.343329	eval-logloss:0.378325
[1737]	train-logloss:0.343312	eval-logloss:0.378325
[1738]	train-logloss:0.343292	eval-logloss:0.378322
[1739]	train-logloss:0.34327	eval-logloss:0.378321
Stopping. Best iteration:
[1724]	train-logloss:0.343519	eval-logloss:0.378319

In [117]:
gbm.predict(dfinal)

array([ 0.91669607,  0.94653118,  0.94285655, ...,  0.88123316,
        0.96030611,  0.68117779], dtype=float32)

In [118]:
df_submission.project_is_approved = gbm.predict(dfinal)

In [119]:
df_submission.head()

        id  project_is_approved
0  p233245             0.916696
1  p096795             0.946531
2  p236235             0.942857
3  p233680             0.862211
4  p171879             0.867072

In [120]:
df_submission.to_csv('XGBOOST_2.csv', index = False)